<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YourCompany.Dapper\YourCompany.Dapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="YourCompany.ConsoleProgram" />
  </ItemGroup>

</Project>