// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore;

#nullable disable

namespace YourCompany.EFCore.Sqlite.CustomConfigurationMigrations
{
    [DbContext(typeof(YourCompanyDbContext<CustomConfiguration>))]
    [Migration("20260502192921_ItsAlive")]
    partial class ItsAlive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("BINARY")
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Column2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
<<<<<<< HEAD
                        .HasName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_PK_Entity");

                    b.ToTable("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_Entity");
=======
                        .HasName("examples_configuration_efcore_hosting_migration_run_PK_Entity");

                    b.ToTable("examples_configuration_efcore_hosting_migration_run_Entity");
>>>>>>> refs/rewritten/2-persistman--efcore-hosting-migration-run
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WithCrossCuttingFeatureData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
<<<<<<< HEAD
                        .HasName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_PK_ReusableEntity");

                    b.ToTable("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_ReusableEntity");
=======
                        .HasName("examples_configuration_efcore_hosting_migration_run_PK_ReusableEntity");

                    b.ToTable("examples_configuration_efcore_hosting_migration_run_ReusableEntity");
>>>>>>> refs/rewritten/2-persistman--efcore-hosting-migration-run
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeDataPutAwayForRareUseCases", "NonModularManualWayToMixIn", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Column1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column3")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column4")
                                .HasColumnType("TEXT");

                            b1.HasKey("EntityId")
<<<<<<< HEAD
                                .HasName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_PK_EntityMixin");

                            b1.ToTable("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_EntityMixin");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_FK_EntityMixin_Entity_EntityId");
=======
                                .HasName("examples_configuration_efcore_hosting_migration_run_PK_EntityMixin");

                            b1.ToTable("examples_configuration_efcore_hosting_migration_run_EntityMixin");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_configuration_efcore_hosting_migration_run_FK_EntityMixin_Entity_EntityId");
>>>>>>> refs/rewritten/2-persistman--efcore-hosting-migration-run
                        });

                    b.OwnsMany("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeOwnedCollection", "TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Column1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column3")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column4")
                                .HasColumnType("TEXT");

                            b1.Property<int>("EntityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id")
<<<<<<< HEAD
                                .HasName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_PK_EntityOwnedCollection");

                            b1.HasIndex("EntityId")
                                .HasDatabaseName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_IX_EntityOwnedCollection_EntityId");

                            b1.ToTable("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_EntityOwnedCollection");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_FK_EntityOwnedCollection_Entity_EntityId");
=======
                                .HasName("examples_configuration_efcore_hosting_migration_run_PK_EntityOwnedCollection");

                            b1.HasIndex("EntityId")
                                .HasDatabaseName("examples_configuration_efcore_hosting_migration_run_IX_EntityOwnedCollection_EntityId");

                            b1.ToTable("examples_configuration_efcore_hosting_migration_run_EntityOwnedCollection");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_configuration_efcore_hosting_migration_run_FK_EntityOwnedCollection_Entity_EntityId");
>>>>>>> refs/rewritten/2-persistman--efcore-hosting-migration-run
                        });

                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingToManuallyLinkEveryTime", "SomeReusableStuffLink", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReusableEntityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("EntityId")
<<<<<<< HEAD
                                .HasName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_PK_EntityLinkToReusableEntity");

                            b1.HasIndex("ReusableEntityId")
                                .HasDatabaseName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_IX_EntityLinkToReusableEntity_ReusableEntityId");

                            b1.ToTable("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_EntityLinkToReusableEntity");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_FK_EntityLinkToReusableEntity_Entity_EntityId");
=======
                                .HasName("examples_configuration_efcore_hosting_migration_run_PK_EntityLinkToReusableEntity");

                            b1.HasIndex("ReusableEntityId")
                                .HasDatabaseName("examples_configuration_efcore_hosting_migration_run_IX_EntityLinkToReusableEntity_ReusableEntityId");

                            b1.ToTable("examples_configuration_efcore_hosting_migration_run_EntityLinkToReusableEntity");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_configuration_efcore_hosting_migration_run_FK_EntityLinkToReusableEntity_Entity_EntityId");
>>>>>>> refs/rewritten/2-persistman--efcore-hosting-migration-run

                            b1.HasOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", null)
                                .WithMany()
                                .HasForeignKey("ReusableEntityId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
<<<<<<< HEAD
                                .HasConstraintName("examples_oltp_di_efcore_handle_specifications_only_the_rest_is_covered_FK_EntityLinkToReusableEntity_ReusableEntity_ReusableEntityId");
=======
                                .HasConstraintName("examples_configuration_efcore_hosting_migration_run_FK_EntityLinkToReusableEntity_ReusableEntity_ReusableEntityId");
>>>>>>> refs/rewritten/2-persistman--efcore-hosting-migration-run
                        });

                    b.Navigation("NonModularManualWayToMixIn");

                    b.Navigation("SomeReusableStuffLink");

                    b.Navigation("TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt");
                });
#pragma warning restore 612, 618
        }
    }
}
