<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YourCompany.OLTP.StateOwnership.Reflection\YourCompany.OLTP.StateOwnership.Reflection.csproj" />
    <ProjectReference Include="..\YourCompany.OLTP.StateOwnership.TransactionalComposition\YourCompany.OLTP.StateOwnership.TransactionalComposition.csproj" />
    <ProjectReference Include="..\YourCompany.Reflection\YourCompany.Reflection.csproj" />
  </ItemGroup>

</Project>
