// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourCompany.Configuration.EFCore;

#nullable disable

namespace YourCompany.EFCore.PostgreSQL.YourCompanyDbContextConfigurationMigrations
{
    [DbContext(typeof(YourCompanyDbContext<YourCompanyDbContextConfiguration>))]
    partial class YourCompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("C")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Column1")
                        .HasColumnType("integer");

                    b.Property<string>("Column2")
                        .HasColumnType("text");

                    b.Property<string>("Column3")
                        .HasColumnType("text");

                    b.Property<string>("Column4")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("ex_configu_e_PK_Entity");

                    b.ToTable("ex_configu_e_Entity");
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("WithCrossCuttingFeatureData")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("ex_configu_e_PK_ReusableEntity");

                    b.ToTable("ex_configu_e_ReusableEntity");
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeDataPutAwayForRareUseCases", "NonModularManualWayToMixIn", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<string>("Column1")
                                .HasColumnType("text");

                            b1.Property<string>("Column2")
                                .HasColumnType("text");

                            b1.Property<string>("Column3")
                                .HasColumnType("text");

                            b1.Property<string>("Column4")
                                .HasColumnType("text");

                            b1.HasKey("EntityId")
                                .HasName("ex_configu_e_PK_EntityMixin");

                            b1.ToTable("ex_configu_e_EntityMixin");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("ex_configu_e_FK_EntityMixin_Entity_EntityId");
                        });

                    b.OwnsMany("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeOwnedCollection", "TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Column1")
                                .HasColumnType("text");

                            b1.Property<string>("Column2")
                                .HasColumnType("text");

                            b1.Property<string>("Column3")
                                .HasColumnType("text");

                            b1.Property<string>("Column4")
                                .HasColumnType("text");

                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.HasKey("Id")
                                .HasName("ex_configu_e_PK_EntityOwnedCollection");

                            b1.HasIndex("EntityId")
                                .HasDatabaseName("ex_configu_e_IX_EntityOwnedCollection_EntityId");

                            b1.ToTable("ex_configu_e_EntityOwnedCollection");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("ex_configu_e_FK_EntityOwnedCollection_Entity_EntityId");
                        });

                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingToManuallyLinkEveryTime", "SomeReusableStuffLink", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("ReusableEntityId")
                                .HasColumnType("integer");

                            b1.HasKey("EntityId")
                                .HasName("ex_configu_e_PK_EntityLinkToReusableEntity");

                            b1.HasIndex("ReusableEntityId")
                                .HasDatabaseName("ex_configu_e_IX_EntityLinkToReusableEntity_ReusableEntityId");

                            b1.ToTable("ex_configu_e_EntityLinkToReusableEntity");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("ex_configu_e_FK_EntityLinkToReusableEntity_Entity_EntityId");

                            b1.HasOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", null)
                                .WithMany()
                                .HasForeignKey("ReusableEntityId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("ex_configu_e_FK_EntityLinkToReusableEntity_ReusableEntiCB4546B");
                        });

                    b.Navigation("NonModularManualWayToMixIn");

                    b.Navigation("SomeReusableStuffLink");

                    b.Navigation("TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt");
                });
#pragma warning restore 612, 618
        }
    }
}
