<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="YourCompany.OLTP.RecordsManagement" />
    <InternalsVisibleTo Include="YourCompany.OLTP.RecordsManagement.DI" />
  </ItemGroup>

</Project>
