using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.CompilerServices;
using YourCompany.OLTP.StateOwnership;
using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public static partial class RecordsDataAccess
    {
        public abstract class Proxy : IStarting,
            IAfterSortingByIdsWithoutReading,
            IAfterSortingByIds,
            IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting>,
            IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues>,
            IReadOnlyWithoutIds<PrimaryKey>,
            IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>,
            IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>,
            IReadBeforeModifying<PrimaryKey>,
            IReadBeforeModifying<PrimaryKey.AfterAlternateSorting>,
            IReadBeforeModifying<PrimaryKey.WithoutExtraValues>,
            IReadBeforeModifyingIdentity<PrimaryKey>,
            IReadBeforeModifyingIdentity<PrimaryKey.AfterAlternateSorting>,
            IReadBeforeModifyingIdentity<PrimaryKey.WithoutExtraValues>,
            IModifying,
            IFinish
        {
            private readonly IStarting _original;

            protected State.AfterSorting? AfterSorting { get; private set; }
            protected State.FinishingChain? FinishingChain { get; private set; }

            int IRecordsBatchSizeLimit.MaxRecordsInBatch => _original.MaxRecordsInBatch;
            IReadBeforeModifyingIdentity<PrimaryKey> IReadBeforeModifying<PrimaryKey>.Next => this;
            IReadBeforeModifyingIdentity<PrimaryKey.AfterAlternateSorting> IReadBeforeModifying<PrimaryKey.AfterAlternateSorting>.Next => this;
            IReadBeforeModifyingIdentity<PrimaryKey.WithoutExtraValues> IReadBeforeModifying<PrimaryKey.WithoutExtraValues>.Next => this;
            IModifying IReadBeforeModifyingIdentity<PrimaryKey>.Next => this;
            IModifying IReadBeforeModifyingIdentity<PrimaryKey.AfterAlternateSorting>.Next => this;
            IModifying IReadBeforeModifyingIdentity<PrimaryKey.WithoutExtraValues>.Next => this;
            IReadIdentity<PrimaryKey> IReadOnly<PrimaryKey>.Next => this;
            IFinish IReadIdentity<PrimaryKey>.Next => this;
            IFinish IReadIdentity<PrimaryKey.AfterAlternateSorting>.Next => this;
            IFinish IReadIdentity<PrimaryKey.WithoutExtraValues>.Next => this;
            IReadIdentity<PrimaryKey.AfterAlternateSorting> IReadOnly<PrimaryKey.AfterAlternateSorting>.Next => this;
            IReadIdentity<PrimaryKey.WithoutExtraValues> IReadOnly<PrimaryKey.WithoutExtraValues>.Next => this;
            IFinish IModifying.Next => this;

            protected Proxy(IStarting original) => _original = original ?? throw new ArgumentNullException(nameof(original));

            IAfterSortingByIdsWithoutReading IStarting.ByIdsWithoutForcedReadIfModifying(IReadOnlyList<PrimaryKey> ids)
            {
                SetAfterSorting(new State.AfterSorting(_original.ByIdsWithoutForcedReadIfModifying(ids)));
                return AfterSorting.HasValue ? this : null;
            }

            IAfterSortingByIds IStarting.ByIds(IReadOnlyList<Identity> ids, bool skipMissingOrPreventCreation)
            {
                SetAfterSorting(new State.AfterSorting(_original.ByIds(ids, skipMissingOrPreventCreation)));
                return AfterSorting.HasValue ? this : null;
            }

            IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting> IStarting.After(Identity afterId)
            {
                SetAfterSorting(new State.AfterSorting(_original.After(afterId)));
                return AfterSorting.HasValue ? this : null;
            }

            IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues> IStarting.NoSorting()
            {
                SetAfterSorting(new State.AfterSorting(_original.NoSorting()));
                return AfterSorting.HasValue ? this : null;
            }

            IModifying IAfterSortingByIdsWithoutReading.ForModifyingOrCreatingByIdsWithoutReading()
            {
                SetFinishingChain(CreateModifyingOrCreatingByIdsWithoutReadingFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadOnly<PrimaryKey> IAfterSortingByIdsForReadOnly.ForReadOnlyByIdsWithoutRecordsData()
            {
                SetFinishingChain(CreateReadOnlyWithoutRecordsDataFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadOnly<PrimaryKey> IAfterSortingByIdsForReadOnly.ForReadOnlyByIdsWithRecordsData()
            {
                SetFinishingChain(CreateReadOnlyWithRecordsDataFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadBeforeModifying<PrimaryKey> IAfterSortingByIdsForModifying.ForModifyingAfterReadingByIds()
            {
                SetFinishingChain(CreateModifyingAfterReadingFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData.ForReadOnlyWithoutRecordsData()
            {
                SetFinishingChain(CreateReadOnlyWithoutRecordsDataFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>
                IAfterSortingWithoutIdsForReadOnly<PrimaryKey.AfterAlternateSorting>.ForReadOnlyWithRecordsData()
            {
                SetFinishingChain(CreateReadOnlyWithRecordsDataFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                IAfterSortingWithoutIdsForReadOnly<PrimaryKey.WithoutExtraValues>.ForReadOnlyWithRecordsData()
            {
                SetFinishingChain(CreateReadOnlyWithRecordsDataFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadBeforeModifying<PrimaryKey.AfterAlternateSorting>
                IAfterSortingWithoutIdsForModifying<PrimaryKey.AfterAlternateSorting>.ForModifyingAfterReading()
            {
                SetFinishingChain(CreateModifyingAfterReadingFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            IReadBeforeModifying<PrimaryKey.WithoutExtraValues>
                IAfterSortingWithoutIdsForModifying<PrimaryKey.WithoutExtraValues>.ForModifyingAfterReading()
            {
                SetFinishingChain(CreateModifyingAfterReadingFinishingChain());
                return FinishingChain.HasValue ? this : null;
            }

            bool IFilterBeforeRead.FilterAfterSorting(object specification) => FilterAfterSorting(specification);
            protected bool FilterAfterSorting(object specification)
            {
                var filterBeforeRead = AfterSorting.HasValue
                    ? GetAfterSorting().FilterBeforeRead
                    : FinishingChain.HasValue
                        ? GetFinishingChain().FilterBeforeRead
                        : throw new ApplicationException("!AfterSorting.HasValue && !FinishingChain.HasValue");
                return filterBeforeRead != null && filterBeforeRead.FilterAfterSorting(specification);
            }

            Task<int> IReadOnly.ReadWithoutModifying(
                int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                => ReadWithoutModifying(batchSize, recordsCountToSkip, cancellationToken);

            protected Task<int> ReadWithoutModifying(int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                => FinishReading(GetFinishingChain().ReadWithoutModifying(batchSize, recordsCountToSkip, cancellationToken));

            bool IAllowAtomicUpdateWithUnchangedRecordsDataRead.ChangeEachRecordToMatch(object specification)
                => GetFinishingChain().ChangeEachRecordToMatch(specification);

            Task<int> IReadBeforeModifying.ReadAndLockForChangesPersisting(
                int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                => ReadAndLockForChangesPersisting(batchSize, recordsCountToSkip, cancellationToken);

            protected Task<int> ReadAndLockForChangesPersisting(int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                => FinishReading(GetFinishingChain().ReadAndLockForChangesPersisting(batchSize, recordsCountToSkip, cancellationToken));

            PrimaryKey IReadIdentity<PrimaryKey>.GetReadRecordIdentity(
                int recordIndex, Identity originalIdentityWhenByIds)
                => (PrimaryKey)GetFinishingChain().GetReadRecordIdentity(recordIndex, originalIdentityWhenByIds);

            PrimaryKey.AfterAlternateSorting IReadIdentity<PrimaryKey.AfterAlternateSorting>.GetReadRecordIdentity(
                int recordIndex, Identity originalIdentityWhenByIds)
                => (PrimaryKey.AfterAlternateSorting)GetFinishingChain().GetReadRecordIdentity(recordIndex, originalIdentityWhenByIds);

            PrimaryKey.WithoutExtraValues IReadIdentity<PrimaryKey.WithoutExtraValues>.GetReadRecordIdentity(
                int recordIndex, Identity originalIdentityWhenByIds)
                => (PrimaryKey.WithoutExtraValues)GetFinishingChain().GetReadRecordIdentity(recordIndex, originalIdentityWhenByIds);

            object IModifying.CreateRecordDataForSettingChangedProperties(int recordIndex, PrimaryKey primaryKey)
                => CreateRecordDataForSettingChangedProperties(recordIndex, primaryKey);

            protected object CreateRecordDataForSettingChangedProperties(int recordIndex, PrimaryKey primaryKey)
                => GetFinishingChain().CreateRecordDataForSettingChangedProperties(recordIndex, primaryKey);

            bool IModifying.ChangeSpecifiedRecordToMatch(int recordIndex, PrimaryKey primaryKey, object specification)
                => GetFinishingChain().ChangeSpecifiedRecordToMatch(recordIndex, primaryKey, specification);

            Task IModifying.PersistChanges(CancellationToken cancellationToken)
                => PersistChanges(cancellationToken);

            protected Task PersistChanges(CancellationToken cancellationToken)
                => FinishModifying(GetFinishingChain().PersistChanges(cancellationToken));

            object IModifying.GetLockedRecordDataWithoutChanges(int recordIndex, PrimaryKey primaryKey)
                => GetFinishingChain().GetLockedRecordDataWithoutChanges(recordIndex, primaryKey);

            Task IFinish.Finish(CancellationToken cancellationToken) => Finish(cancellationToken);
            protected Task Finish(CancellationToken cancellationToken) => GetFinishingChain().Finish(cancellationToken);

            object IFinish.GetRecordDataAfterAccess(int recordIndex, PrimaryKey primaryKey)
                => GetFinishingChain().GetRecordDataAfterAccess(recordIndex, primaryKey);

            Task IAsyncDisposableWithCancellation.Dispose(CancellationToken cancellationToken, Exception runException)
                => _original.Dispose(cancellationToken, runException);

            protected void SetAfterSorting(State.AfterSorting afterSorting)
            {
                if (AfterSorting.HasValue) throw new ApplicationException("AfterSorting.HasValue");
                if (FinishingChain.HasValue) throw new ApplicationException("FinishingChain.HasValue");
                if (!StructHelper.IsZeroed(afterSorting)) AfterSorting = afterSorting;
            }

            protected State.FinishingChain CreateModifyingOrCreatingByIdsWithoutReadingFinishingChain()
                => new State.FinishingChain(GetAfterSorting().ForModifyingOrCreatingByIdsWithoutReading());

            protected State.FinishingChain CreateReadOnlyWithoutRecordsDataFinishingChain()
                => new State.FinishingChain(GetAfterSorting().ForReadOnlyWithoutRecordsData());

            protected State.FinishingChain CreateReadOnlyWithRecordsDataFinishingChain()
                => new State.FinishingChain(GetAfterSorting().ForReadOnlyWithRecordsData());

            protected State.FinishingChain CreateModifyingAfterReadingFinishingChain()
                => new State.FinishingChain(GetAfterSorting().ForModifyingAfterReading());

            protected State.AfterSorting GetAfterSorting()
            {
                if (!AfterSorting.HasValue) throw new ApplicationException("!AfterSorting.HasValue");
                if (FinishingChain.HasValue) throw new ApplicationException("FinishingChain.HasValue");
                return AfterSorting.Value;
            }

            protected void SetFinishingChain(State.FinishingChain finishingChain)
            {
                if (!AfterSorting.HasValue) throw new ApplicationException("!AfterSorting.HasValue");
                if (FinishingChain.HasValue) throw new ApplicationException("FinishingChain.HasValue");
                if (!StructHelper.IsZeroed(finishingChain)) FinishingChain = finishingChain;
            }

            protected async Task<int> FinishReading(Task<int> reading)
            {
                int readRecordsCount = await reading;
                FinishingChain = GetFinishingChain().FinishReading(readRecordsCount);
                return readRecordsCount;
            }

            protected async Task FinishModifying(Task<IFinish> modifying)
            {
                var finish = await modifying;
                FinishingChain = GetFinishingChain().FinishModifying(finish);
            }

            protected State.FinishingChain GetFinishingChain()
            {
                if (AfterSorting.HasValue) throw new ApplicationException("AfterSorting.HasValue");
                if (!FinishingChain.HasValue) throw new ApplicationException("!FinishingChain.HasValue");
                return FinishingChain.Value;
            }
        }
    }
}