using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public static partial class RecordsDataAccess
    {
        internal readonly partial struct State
        {
            internal readonly struct AfterSorting
            {
                private readonly IAfterSortingByIdsWithoutReading _byIdsWithoutReading;
                private readonly IAfterSortingByIds _byIds;

                private readonly IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting>
                    _withoutIdsAfterAlternateSorting;

                private readonly IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues>
                    _withoutIdsWithoutExtraValues;

                internal bool ForceReadByIdsForIdentityReplacementIfModifying => _byIds != null;
                internal IFilterBeforeRead FilterBeforeRead { get; }

                internal AfterSorting(IAfterSortingByIdsWithoutReading byIdsWithoutReading)
                    : this() => _byIdsWithoutReading = byIdsWithoutReading;
                    
                internal AfterSorting(IAfterSortingByIds byIds) : this() => _byIds = byIds;

                internal AfterSorting(IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting> afterSortingWithoutIds)
                    : this() => FilterBeforeRead = _withoutIdsAfterAlternateSorting = afterSortingWithoutIds;

                internal AfterSorting(IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues> afterSortingWithoutIds)
                    : this() => FilterBeforeRead = _withoutIdsWithoutExtraValues = afterSortingWithoutIds;

                internal IModifying ForModifyingOrCreatingByIdsWithoutReading()
                    => _byIdsWithoutReading?.ForModifyingOrCreatingByIdsWithoutReading();

                internal ReadIdentity.ForReadWithoutModifying ForReadOnlyWithoutRecordsData()
                    => _byIdsWithoutReading != null
                        ? new ReadIdentity.ForReadWithoutModifying(
                            _byIdsWithoutReading.ForReadOnlyByIdsWithoutRecordsData(), withRecordsData: false)
                        : _byIds != null
                            ? new ReadIdentity.ForReadWithoutModifying(
                                _byIds.ForReadOnlyByIdsWithoutRecordsData(), withRecordsData: false)
                            : _withoutIdsAfterAlternateSorting != null
                                ? new ReadIdentity.ForReadWithoutModifying(
                                    _withoutIdsAfterAlternateSorting.ForReadOnlyWithoutRecordsData(), withRecordsData: false)
                                : _withoutIdsWithoutExtraValues != null
                                    ? new ReadIdentity.ForReadWithoutModifying(
                                        _withoutIdsWithoutExtraValues.ForReadOnlyWithoutRecordsData(), withRecordsData: false)
                                    : default;

                internal ReadIdentity.ForReadWithoutModifying ForReadOnlyWithRecordsData()
                    => _byIdsWithoutReading != null
                        ? new ReadIdentity.ForReadWithoutModifying(
                            _byIdsWithoutReading.ForReadOnlyByIdsWithRecordsData(), withRecordsData: true)
                        : _byIds != null
                            ? new ReadIdentity.ForReadWithoutModifying(
                                _byIds.ForReadOnlyByIdsWithRecordsData(), withRecordsData: true)
                            : _withoutIdsAfterAlternateSorting != null
                                ? new ReadIdentity.ForReadWithoutModifying(
                                    _withoutIdsAfterAlternateSorting.ForReadOnlyWithRecordsData(), withRecordsData: true)
                                : _withoutIdsWithoutExtraValues != null
                                    ? new ReadIdentity.ForReadWithoutModifying(
                                        _withoutIdsWithoutExtraValues.ForReadOnlyWithRecordsData(), withRecordsData: true)
                                    : default;

                internal ReadIdentity.ForReadBeforeModifying ForModifyingAfterReading()
                    => _byIdsWithoutReading != null
                        ? new ReadIdentity.ForReadBeforeModifying(
                            _byIdsWithoutReading.ForModifyingAfterReadingByIds())
                        : _byIds != null
                            ? new ReadIdentity.ForReadBeforeModifying(
                                _byIds.ForModifyingAfterReadingByIds())
                            : _withoutIdsAfterAlternateSorting != null
                                ? new ReadIdentity.ForReadBeforeModifying(
                                    _withoutIdsAfterAlternateSorting.ForModifyingAfterReading())
                                : _withoutIdsWithoutExtraValues != null
                                    ? new ReadIdentity.ForReadBeforeModifying(
                                        _withoutIdsWithoutExtraValues.ForModifyingAfterReading())
                                    : default;
            }
        }
    }
}