using System;
using YourCompany.CompilerServices;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public static partial class RecordsDataAccess
    {
        public readonly partial struct State
        {
            public readonly struct ReadIdentity
            {
                private readonly IReadIdentity<PrimaryKey> _afterSortingByIds;
                private readonly IReadIdentity<PrimaryKey.AfterAlternateSorting> _afterAlternateSorting;
                private readonly IReadIdentity<PrimaryKey.WithoutExtraValues> _withoutExtraValues;

                internal bool ReadOnlyRecordsIncluded { get; }
                internal IFilterBeforeRead FilterBeforeRead { get; }
                internal int? ReadRecordsCount { get; }

                private ReadIdentity(ReadIdentity beforeRead, int readRecordsCount)
                {
                    if (StructHelper.IsZeroed(beforeRead)) throw new ApplicationException("StructHelper.IsZeroed(beforeRead)");
                    if (beforeRead.ReadRecordsCount.HasValue) throw new ApplicationException("beforeRead.ReadRecordsCount.HasValue");
                    if (readRecordsCount < 0) throw new ApplicationException("readRecordsCount < 0");
                    _afterSortingByIds = beforeRead._afterSortingByIds;
                    _afterAlternateSorting = beforeRead._afterAlternateSorting;
                    _withoutExtraValues = beforeRead._withoutExtraValues;
                    FilterBeforeRead = null;
                    ReadOnlyRecordsIncluded = beforeRead.ReadOnlyRecordsIncluded;
                    ReadRecordsCount = readRecordsCount;
                }

                private ReadIdentity(IReadIdentity<PrimaryKey> afterSortingByIds, bool readOnlyRecordsIncluded) : this()
                {
                    _afterSortingByIds = afterSortingByIds;
                    ReadOnlyRecordsIncluded = afterSortingByIds != null && readOnlyRecordsIncluded;
                }

                private ReadIdentity(
                    IReadIdentity<PrimaryKey.AfterAlternateSorting> afterAlternateSorting,
                    bool readOnlyRecordsIncluded,
                    IFilterBeforeRead filterBeforeRead)
                    : this()
                {
                    if (afterAlternateSorting == null && filterBeforeRead != null) throw new ApplicationException("afterAlternateSorting == null && filterBeforeRead != null");
                    _afterAlternateSorting = afterAlternateSorting;
                    ReadOnlyRecordsIncluded = afterAlternateSorting != null && readOnlyRecordsIncluded;
                    FilterBeforeRead = filterBeforeRead;
                }

                private ReadIdentity(
                    IReadIdentity<PrimaryKey.WithoutExtraValues> withoutExtraValues,
                    bool readOnlyRecordsIncluded,
                    IFilterBeforeRead filterBeforeRead)
                    : this()
                {
                    if (withoutExtraValues == null && filterBeforeRead != null) throw new ApplicationException("withoutExtraValues == null && filterBeforeRead != null");
                    _withoutExtraValues = withoutExtraValues;
                    ReadOnlyRecordsIncluded = withoutExtraValues != null && readOnlyRecordsIncluded;
                    FilterBeforeRead = filterBeforeRead;
                }

                internal ReadIdentity FinishReading(int readRecordsCount) => new ReadIdentity(this, readRecordsCount);

                internal Identity GetReadRecordIdentity(int recordIndex, Identity originalIdentityWhenSpecified)
                {
                    if (!ReadRecordsCount.HasValue) throw new ApplicationException("!ReadRecordsCount.HasValue");
                    if (FilterBeforeRead != null) throw new ApplicationException("FilterBeforeRead != null");

                    if (_afterSortingByIds != null)
                        return _afterSortingByIds.GetReadRecordIdentity(recordIndex, originalIdentityWhenSpecified);

                    if (_afterAlternateSorting != null)
                        return _afterAlternateSorting.GetReadRecordIdentity(recordIndex, originalIdentityWhenSpecified);

                    if (_withoutExtraValues != null)
                        return _withoutExtraValues.GetReadRecordIdentity(recordIndex, originalIdentityWhenSpecified);

                    throw new ApplicationException("_afterSortingByIds == null && _afterAlternateSorting == null && _withoutExtraValues == null");
                }

                public readonly struct ForReadWithoutModifying
                {
                    internal ReadIdentity Base { get; }
                    internal IReadOnly ReadOnly { get; }
                    internal IFinish Finish { get; }

                    public ForReadWithoutModifying(IReadOnly<PrimaryKey> readOnly, bool withRecordsData)
                    {
                        Base = new ReadIdentity(readOnly?.Next, withRecordsData);
                        ReadOnly = readOnly;
                        Finish = Base._afterSortingByIds?.Next;
                    }

                    public ForReadWithoutModifying(
                        IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting> readOnly,
                        bool withRecordsData)
                    {
                        Base = new ReadIdentity(
                            readOnly?.Next, readOnlyRecordsIncluded: withRecordsData, filterBeforeRead: readOnly);
                        ReadOnly = readOnly;
                        Finish = Base._afterAlternateSorting?.Next;
                    }

                    public ForReadWithoutModifying(
                        IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues> readOnly,
                        bool withRecordsData)
                    {
                        Base = new ReadIdentity(
                            readOnly?.Next, readOnlyRecordsIncluded: withRecordsData, filterBeforeRead: readOnly);
                        ReadOnly = readOnly;
                        Finish = Base._withoutExtraValues?.Next;
                    }
                }

                public readonly struct ForReadBeforeModifying
                {
                    internal ReadIdentity Base { get; }
                    internal IAllowAtomicUpdateWithUnchangedRecordsDataRead ReadBeforeModifying { get; }
                    internal IModifying Modifying { get; }

                    public ForReadBeforeModifying(IReadBeforeModifying<PrimaryKey> readBeforeModifying)
                    {
                        var readBeforeModifyingIdentity = readBeforeModifying?.Next;
                        Base = new ReadIdentity(readBeforeModifyingIdentity, readOnlyRecordsIncluded: false);
                        ReadBeforeModifying = readBeforeModifying;
                        Modifying = readBeforeModifyingIdentity?.Next;
                    }

                    public ForReadBeforeModifying(
                        IReadBeforeModifying<PrimaryKey.AfterAlternateSorting> readBeforeModifying)
                    {
                        var readBeforeModifyingIdentity = readBeforeModifying?.Next;
                        Base = new ReadIdentity(
                            readBeforeModifyingIdentity, readOnlyRecordsIncluded: false, filterBeforeRead: null);
                        ReadBeforeModifying = readBeforeModifying;
                        Modifying = readBeforeModifyingIdentity?.Next;
                    }

                    public ForReadBeforeModifying(
                        IReadBeforeModifying<PrimaryKey.WithoutExtraValues> readBeforeModifying)
                    {
                        var readBeforeModifyingIdentity = readBeforeModifying?.Next;
                        Base = new ReadIdentity(
                            readBeforeModifyingIdentity, readOnlyRecordsIncluded: false, filterBeforeRead: null);
                        ReadBeforeModifying = readBeforeModifying;
                        Modifying = readBeforeModifyingIdentity?.Next;
                    }
                }
            }
        }
    }
}