using System;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.CompilerServices;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public static partial class RecordsDataAccess
    {
        public readonly partial struct State
        {
            public readonly struct FinishingChain
            {
                private readonly IReadOnly _readOnly;
                private readonly IAllowAtomicUpdateWithUnchangedRecordsDataRead _readBeforeModifying;
                private readonly ReadIdentity? _readIdentity;
                private readonly IModifying _modifying;
                private readonly IFinish _finish;

                public bool ReadOnlyRecordsIncluded => _readIdentity?.ReadOnlyRecordsIncluded ?? false;
                internal IFilterBeforeRead FilterBeforeRead => _readIdentity?.FilterBeforeRead;
                internal int? ReadRecordsCount => _readIdentity?.ReadRecordsCount;

                internal FinishingChain(ReadIdentity.ForReadWithoutModifying readIdentity)
                {
                    if (StructHelper.IsZeroed(readIdentity)) throw new ApplicationException("StructHelper.IsZeroed(readIdentity)");
                    _readBeforeModifying = null;
                    _readOnly = readIdentity.ReadOnly;
                    _readIdentity = readIdentity.Base;
                    _modifying = null;
                    _finish = readIdentity.Finish;
                }

                internal FinishingChain(ReadIdentity.ForReadBeforeModifying readIdentity)
                {
                    if (StructHelper.IsZeroed(readIdentity)) throw new ApplicationException("StructHelper.IsZeroed(readIdentity)");
                    if (readIdentity.Base.FilterBeforeRead != null) throw new ApplicationException("readIdentity.Base.FilterBeforeRead != null");
                    _readBeforeModifying = readIdentity.ReadBeforeModifying;
                    _readOnly = null;
                    _readIdentity = readIdentity.Base;
                    _modifying = readIdentity.Modifying;
                    _finish = null;
                }

                internal FinishingChain(IModifying modifying)
                {
                    _readBeforeModifying = null;
                    _readOnly = null;
                    _readIdentity = null;
                    _modifying = modifying ?? throw new ArgumentNullException(nameof(modifying));
                    _finish = null;
                }

                private FinishingChain(FinishingChain beforeRead, int readRecordsCount)
                {
                    beforeRead.EnsureIsBeforeRead();
                    var readIdentity = beforeRead._readIdentity ?? throw new ApplicationException("!beforeRead._readIdentity.HasValue");
                    _readBeforeModifying = null;
                    _readOnly = null;
                    _readIdentity = readIdentity.FinishReading(readRecordsCount);
                    _modifying = beforeRead._modifying;
                    _finish = beforeRead._finish;
                }

                private FinishingChain(FinishingChain modifying, IFinish finish)
                {
                    modifying.WhenNoReadAllowing().EnsureIsModifying();
                    _readBeforeModifying = null;
                    _readOnly = null;
                    _readIdentity = modifying._readIdentity;
                    _modifying = modifying._modifying ?? throw new ApplicationException("modifying._modifying == null");
                    _finish = finish ?? throw new ArgumentNullException(nameof(finish));
                }

                public void EnsureIsBeforeRead() => WhenBeforeRead();
                public void EnsureIsBeforeFinishing() => WhenBeforeFinishing();
                public void EnsureIsReadOnly() => WhenReadOnly();
                public void EnsureIsModifying() => WhenModifying();
                public void EnsureIsAterRead() => WhenAfterRead();
                public void EnsureIsModified() => WhenModified();
                public void EnsureIsFinishing() => WhenFinishing();
                public void EnsureIsNoReadAllowing() => WhenNoReadAllowing();

                public bool ChangeEachRecordToMatch(object specification)
                {
                    if (specification == null) throw new ArgumentNullException(nameof(specification));
                    return WhenModifying()._readBeforeModifying?.ChangeEachRecordToMatch(specification) ?? false;
                }

                internal Task<int> ReadAndLockForChangesPersisting(
                    int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                    => WhenBeforeRead().WhenModifying()._readBeforeModifying.ReadAndLockForChangesPersisting(
                        batchSize, recordsCountToSkip, cancellationToken);

                internal Task<int> ReadWithoutModifying(
                    int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                    => WhenBeforeRead().WhenReadOnly()._readOnly.ReadWithoutModifying(
                        batchSize, recordsCountToSkip, cancellationToken);

                internal FinishingChain FinishReading(int readRecordsCount) => new FinishingChain(this, readRecordsCount);

                public Identity GetReadRecordIdentity(int recordIndex, Identity originalIdentityWhenSpecified)
                {
                    if (recordIndex < 0) throw new ArgumentOutOfRangeException(nameof(recordIndex), recordIndex, message: null);
                    var readIdentity = WhenAfterRead()._readIdentity ?? throw new ApplicationException("!_readIdentity.HasValue");
                    return readIdentity.GetReadRecordIdentity(recordIndex, originalIdentityWhenSpecified);
                }

                internal object CreateRecordDataForSettingChangedProperties(int recordIndex, Identity identity)
                    => WhenModifying().WhenNoReadAllowing()._modifying
                        .CreateRecordDataForSettingChangedProperties(recordIndex, (PrimaryKey)identity);

                public bool ChangeSpecifiedRecordToMatch(
                    int recordIndex, Identity identity, object specification)
                    => WhenModifying().WhenNoReadAllowing()._modifying
                        .ChangeSpecifiedRecordToMatch(recordIndex, (PrimaryKey)identity, specification);

                internal async Task<IFinish> PersistChanges(CancellationToken cancellationToken)
                {
                    await WhenModifying().WhenNoReadAllowing()._modifying.PersistChanges(cancellationToken);
                    return _modifying.Next;
                }

                internal FinishingChain FinishModifying(IFinish finish) => new FinishingChain(this, finish);

                public object GetLockedRecordDataWithoutChanges(int recordIndex, Identity identity)
                    => WhenModified()._modifying.GetLockedRecordDataWithoutChanges(recordIndex, (PrimaryKey)identity);

                internal Task Finish(CancellationToken cancellationToken)
                    => WhenFinishing()._finish.Finish(cancellationToken);

                public object GetRecordDataAfterAccess(int recordIndex, Identity identity)
                    => WhenFinishing()._finish.GetRecordDataAfterAccess(recordIndex, (PrimaryKey)identity);

                internal FinishingChain WhenBeforeRead()
                {
                    if (_readBeforeModifying == null && _readOnly == null)
                        throw new ApplicationException("_readBeforeModifying == null && _readOnly == null");
                    if (!_readIdentity.HasValue) throw new ApplicationException("!_readIdentity.HasValue");
                    return WhenBeforeFinishing();
                }

                internal FinishingChain WhenBeforeFinishing()
                {
                    if (_readBeforeModifying == null && _readOnly == null && _modifying == null)
                        throw new ApplicationException("_readBeforeModifying == null && _readOnly == null && _modifying == null");
                    EnsureReadOnlyConsistent();
                    EnsureReadBeforeModifyingConsistent();
                    if (_modifying != null && _finish != null)
                        throw new ApplicationException("_modifying != null && _finish != null");
                    if (_finish != null && !_readIdentity.HasValue)
                        throw new ApplicationException("_finish != null && !_readIdentity.HasValue");
                    return this;
                }

                internal FinishingChain WhenReadOnly()
                {
                    EnsureReadOnlyConsistent();
                    if (_readBeforeModifying != null) throw new ApplicationException("_readBeforeModifying != null");
                    if (!_readIdentity.HasValue) throw new ApplicationException("!_readIdentity.HasValue");
                    if (_modifying != null) throw new ApplicationException("_modifying != null");
                    if (_finish == null) throw new ApplicationException("_finish == null");
                    return this;
                }

                internal FinishingChain WhenModifying()
                {
                    EnsureReadBeforeModifyingConsistent();
                    if (_readOnly != null) throw new ApplicationException("_readOnly != null");
                    if (_modifying == null) throw new ApplicationException("_modifying == null");
                    if (_finish != null) throw new ApplicationException("_finish != null");
                    return this;
                }

                internal FinishingChain WhenAfterRead()
                {
                    if (!_readIdentity.HasValue) throw new ApplicationException("!_readIdentity.HasValue");
                    return WhenNoReadAllowing();
                }

                internal FinishingChain WhenModified()
                {
                    if (_modifying == null) throw new ApplicationException("_modifying == null");
                    return WhenFinishing();
                }

                internal FinishingChain WhenFinishing()
                {
                    if (_finish == null) throw new ApplicationException("_finish == null");
                    return WhenNoReadAllowing();
                }

                internal FinishingChain WhenNoReadAllowing()
                {
                    if (_readBeforeModifying != null) throw new ApplicationException("_readBeforeModifying != null");
                    if (_readOnly != null) throw new ApplicationException("_readOnly != null");
                    if (_readIdentity.HasValue && _readIdentity.Value.FilterBeforeRead != null)
                        throw new ApplicationException("_readIdentity.HasValue && _readIdentity.Value.FilterBeforeRead != null");
                    if (_readIdentity.HasValue && !_readIdentity.Value.ReadRecordsCount.HasValue)
                        throw new ApplicationException("_readIdentity.HasValue && !_readIdentity.Value.ReadRecordsCount.HasValue");
                    return this;
                }

                private void EnsureReadOnlyConsistent()
                {
                    if (_readOnly != null && _readBeforeModifying != null)
                        throw new ApplicationException("_readOnly != null && _readBeforeModifying != null");
                    if (_readOnly != null && !_readIdentity.HasValue)
                        throw new ApplicationException("!_readIdentity.HasValue");
                    if (_readOnly != null && _readIdentity.Value.FilterBeforeRead == null)
                        throw new ApplicationException("_readOnly != null && _readIdentity.Value.FilterBeforeRead == null");
                    if (_readOnly != null && _readIdentity.Value.ReadRecordsCount.HasValue)
                        throw new ApplicationException("_readOnly != null && _readIdentity.Value.ReadRecordsCount.HasValue");
                    if (_readOnly != null && _modifying != null)
                        throw new ApplicationException("_readOnly != null && _modifying != null");
                }

                private void EnsureReadBeforeModifyingConsistent()
                {
                    if (_readBeforeModifying != null && _readOnly != null)
                        throw new ApplicationException("_readBeforeModifying != null && _readOnly != null");
                    if (_readBeforeModifying != null && !_readIdentity.HasValue)
                        throw new ApplicationException("_readBeforeModifying != null && !_readIdentity.HasValue");
                    if (_readBeforeModifying != null && _readIdentity.Value.FilterBeforeRead != null)
                        throw new ApplicationException("_readBeforeModifying != null && _readIdentity.Value.FilterBeforeRead != null");
                    if (_readBeforeModifying != null && _readIdentity.Value.ReadRecordsCount.HasValue)
                        throw new ApplicationException("_readBeforeModifying != null && _readIdentity.Value.ReadRecordsCount.HasValue");
                    if (_readBeforeModifying != null && _modifying == null)
                        throw new ApplicationException("_readBeforeModifying != null && _modifying == null");
                }
            }
        }
    }
}