using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public static partial class RecordsDataAccess
    {
        public interface IAsyncDisposableWithCancellation
        {
            Task Dispose(CancellationToken cancellationToken, Exception runException = null);
        }

        public interface IStarting : IRecordsBatchSizeLimit, IAsyncDisposableWithCancellation
        {
            IAfterSortingByIdsWithoutReading ByIdsWithoutForcedReadIfModifying(IReadOnlyList<PrimaryKey> ids);
            IAfterSortingByIds ByIds(IReadOnlyList<Identity> ids, bool skipMissingOrPreventCreation);
            IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting> After(Identity afterId);
            IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues> NoSorting();
        }

        public interface IAfterSortingByIdsWithoutReading : IAfterSortingByIds
        {
            IModifying ForModifyingOrCreatingByIdsWithoutReading();
        }

        public interface IAfterSortingByIds : IAfterSortingByIdsForReadOnly, IAfterSortingByIdsForModifying { }

        public interface IAfterSortingByIdsForReadOnly
        {
            IReadOnly<PrimaryKey> ForReadOnlyByIdsWithoutRecordsData();
            IReadOnly<PrimaryKey> ForReadOnlyByIdsWithRecordsData();
        }

        public interface IAfterSortingByIdsForModifying
        {
            IReadBeforeModifying<PrimaryKey> ForModifyingAfterReadingByIds();
        }

        public interface IAfterSortingWithoutIds<TPrimaryKeyReadWithRecordsData> : IFilterBeforeRead,
            IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData,
            IAfterSortingWithoutIdsForReadOnly<TPrimaryKeyReadWithRecordsData>,
            IAfterSortingWithoutIdsForModifying<TPrimaryKeyReadWithRecordsData>
            where TPrimaryKeyReadWithRecordsData : PrimaryKey
        { }

        public interface IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData
        {
            IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues> ForReadOnlyWithoutRecordsData();
        }

        public interface IAfterSortingWithoutIdsForReadOnly<TPrimaryKey> where TPrimaryKey : PrimaryKey
        {
            IReadOnlyWithoutIds<TPrimaryKey> ForReadOnlyWithRecordsData();
        }

        public interface IAfterSortingWithoutIdsForModifying<TPrimaryKey> where TPrimaryKey : PrimaryKey
        {
            IReadBeforeModifying<TPrimaryKey> ForModifyingAfterReading();
        }

        public interface IReadOnlyWithoutIds<TPrimaryKey> : IFilterBeforeRead, IReadOnly<TPrimaryKey>
            where TPrimaryKey : PrimaryKey
        { }

        public interface IFilterBeforeRead
        {
            bool FilterAfterSorting(object specification);
        }

        public interface IReadOnly<TPrimaryKey> : IReadOnly
            where TPrimaryKey : PrimaryKey
        {
            IReadIdentity<TPrimaryKey> Next { get; }
        }

        public interface IReadOnly
        {
            Task<int> ReadWithoutModifying(int batchSize, int recordsCountToSkip, CancellationToken cancellationToken);
        }

        public interface IReadBeforeModifying<TPrimaryKey> : IAllowAtomicUpdateWithUnchangedRecordsDataRead
            where TPrimaryKey : PrimaryKey
        {
            IReadBeforeModifyingIdentity<TPrimaryKey> Next { get; }
        }

        public interface IAllowAtomicUpdateWithUnchangedRecordsDataRead : IReadBeforeModifying
        {
            bool ChangeEachRecordToMatch(object specification);
        }

        public interface IReadBeforeModifying
        {
            Task<int> ReadAndLockForChangesPersisting(int batchSize, int recordsCountToSkip, CancellationToken cancellationToken);
        }

        public interface IReadBeforeModifyingIdentity<TPrimaryKey> : IReadIdentity<TPrimaryKey>
            where TPrimaryKey : PrimaryKey
        {
            new IModifying Next { get; }
        }

        public interface IReadIdentity<TPrimaryKey> where TPrimaryKey : PrimaryKey
        {
            TPrimaryKey GetReadRecordIdentity(int recordIndex, Identity originalIdentityWhenByIds);
            IFinish Next { get; }
        }

        public interface IModifying
        {
            object CreateRecordDataForSettingChangedProperties(int recordIndex, PrimaryKey primaryKey);
            bool ChangeSpecifiedRecordToMatch(int recordIndex, PrimaryKey primaryKey, object specification);
            Task PersistChanges(CancellationToken cancellationToken);
            object GetLockedRecordDataWithoutChanges(int recordIndex, PrimaryKey primaryKey);
            IFinish Next { get; }
        }

        public interface IFinish
        {
            Task Finish(CancellationToken cancellationToken);
            object GetRecordDataAfterAccess(int recordIndex, PrimaryKey primaryKey);
        }
    }
}