using System;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public abstract partial class UniqueKey : Identity
    {
        private UniqueKey() { }

        public PrimaryKey AsPrimaryKey() => this as PrimaryKey;

        public TSorting AsAssignedSortingImplementedWith<TSorting>() where TSorting : Alternate.Sorting
            => AsAssignedBeforeSortingImplementedWith<TSorting>()
                ?? AsAssignedAfterSorting()?.AlternateSorting?.ImplementedWith<TSorting>();

        public TSorting AsAssignedBeforeSortingImplementedWith<TSorting>() where TSorting : Alternate.Sorting
            => AsAssignedBeforeSorting()?.ImplementedWith<TSorting>();

        public Alternate.Sorting AsAssignedBeforeSorting()
        {
            EnsureWasAssigned();
            if (this is Alternate.Sorting alternateSorting) return alternateSorting;
            var withoutExtraValues = AsPrimaryKey()?.AsWithoutExtraValues();
            return withoutExtraValues?.AsOriginalBeforeSorting();
        }

        public PrimaryKey.AfterAlternateSorting AsAssignedAfterSorting()
        {
            EnsureWasAssigned();
            var afterSorting = AsPrimaryKey()?.AsAfterAlternateSorting();
            if (afterSorting != null && afterSorting.AlternateSorting == null)
                throw new ApplicationException("afterSorting != null && afterSorting.AlternateSorting == null");
            return afterSorting;
        }

        protected abstract bool EqualsAfterAssignment(UniqueKey other);
        protected sealed override bool EqualsAfterAssignment(Identity other)
        {
            return other is UniqueKey uniqueKey ? EqualsAfterAssignment(uniqueKey) : other.Equals(this);
        }

        protected abstract int CompareAfterAssignment(UniqueKey other);

        protected sealed override int CompareAfterAssignment(Identity other)
            => other is UniqueKey uniqueKey ? CompareAfterAssignment(uniqueKey) : other.CompareTo(this) * -1;
    }
}