using System;
using System.Collections.Generic;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public static class UniqueKeyExtensions
    {
        public static IReadOnlyList<PrimaryKey> AsPrimaryKeys(this IReadOnlyList<Identity> orderedIdentities)
            => orderedIdentities as IReadOnlyList<PrimaryKey>;

        public static void EnsureSpecifying(this IReadOnlyList<Identity> orderedIdentities)
        {
            for (int recordIndex = 0; recordIndex < orderedIdentities.Count; recordIndex++)
                orderedIdentities[recordIndex].EnsureSpecifying();
        }

        public static void EnsureSpecifying(this Identity identity)
        {
            var uniqueKey = identity as UniqueKey;
            if (uniqueKey == null && identity.CheckExpectsAssignment()) throw new ApplicationException("uniqueKey == null && identity.CheckExpectsAssignment()");
            if (uniqueKey == null) return;

            var primaryKey = uniqueKey.AsPrimaryKey();
            if (primaryKey != null)
            {
                if (primaryKey.AsWithoutExtraValues() == null && primaryKey.AsAssignedAfterSorting() == null)
                    throw new ApplicationException("primaryKey.AsWithoutExtraValues() == null && primaryKey.AsAssignedAfterSorting() == null");
            }
            else
            {
                var assignedSorting = uniqueKey.AsAssignedBeforeSorting();
                if (assignedSorting?.PrefixedPrivatePrimaryKeySortingRequired == true)
                    throw new ApplicationException("assignedSorting?.PrefixedPrivatePrimaryKeySortingRequired == true");
            }
        }
    }
}