using System;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence
{
    public abstract partial class UniqueKey
    {
        public static class Primary
        {
            public abstract class PublicGuidAccompanied : UniqueKey
            {
                public Guid? PublicKey { get; private set; }
                private PublicGuidAccompanied() { }

                public void SetPublicKey(Guid? publicKey)
                {
                    EnsureExpectsAssignment();
                    PublicKey = publicKey;
                    if (CheckAllValuesWereAssigned()) ConfirmAssigned();
                }

                public virtual bool CheckAllValuesWereAssigned() => CheckPublicKeyIsAssigned();
                public bool CheckPublicKeyIsAssigned() => PublicKey.HasValue && PublicKey.Value != Guid.Empty;

                protected override bool EqualsAfterAssignment(UniqueKey other)
                {
                    if (!(other is PublicGuidAccompanied otherKey)) return false;
                    Guid publicKey = PublicKey ?? throw new ApplicationException("!PublicKey.HasValue");
                    Guid otherPublicKey = otherKey.PublicKey ?? throw new ApplicationException("!otherKey.PublicKey.HasValue");
                    return publicKey == otherPublicKey;
                }

                protected override int GetHashCodeAfterAssignment()
                {
                    Guid publicKey = PublicKey ?? throw new ApplicationException("!PublicKey.HasValue");
                    return publicKey.GetHashCode();
                }

                public override string ToString() => PublicKey?.ToString() ?? "N/A";

                public class EqualsOnly : PublicGuidAccompanied
                {
                    public EqualsOnly(Guid publicKey) => SetPublicKey(publicKey);

                    protected sealed override int CompareAfterAssignment(UniqueKey other)
                        => throw new NotSupportedException(nameof(EqualsOnly));
                }

                public abstract class PrivateInsertFailureTolerantAutoGeneratedBigint : PublicGuidAccompanied
                {
                    public long? PrivateKey { get; private set; }
                    private PrivateInsertFailureTolerantAutoGeneratedBigint() { }

                    public WithoutExtraValues AsWithoutExtraValues() => this as WithoutExtraValues;
                    public AfterAlternateSorting AsAfterAlternateSorting() => this as AfterAlternateSorting;

                    public void SetPrivateKey(long? privateKey)
                    {
                        EnsureExpectsAssignment();
                        PrivateKey = privateKey;
                        if (CheckAllValuesWereAssigned()) ConfirmAssigned();
                    }

                    public override bool CheckAllValuesWereAssigned()
                        => base.CheckAllValuesWereAssigned() && CheckPrivateKeyIsAssigned();

                    public bool CheckPrivateKeyIsAssigned() => PrivateKey > 0;

                    protected override bool EqualsAfterAssignment(UniqueKey other)
                    {
                        if (other is EqualsOnly publicKeyEqualsOnly) return base.EqualsAfterAssignment(publicKeyEqualsOnly);
                        if (!(other is PrimaryKey otherKey)) return false;
                        long privateKey = PrivateKey ?? throw new ApplicationException("!PrivateKey.HasValue");
                        long otherPrivateKey = otherKey.PrivateKey ?? throw new ApplicationException("!otherKey.PrivateKey.HasValue");
                        bool privateKeysEqual = privateKey == otherPrivateKey;
                        bool publicKeysEqual = base.EqualsAfterAssignment(other);
                        if (publicKeysEqual != privateKeysEqual) throw new ApplicationException("publicKeysEqual != privateKeysEqual");
                        return publicKeysEqual;
                    }

                    public override string ToString() => $"{base.ToString()} : {PrivateKey?.ToString() ?? "N/A"}";

                    public class WithoutExtraValues : PrimaryKey
                    {
                        public Identity OriginalIdentityReference { get; }

                        public WithoutExtraValues(Identity originalIdentityReference = null)
                        {
                            if (originalIdentityReference is PrimaryKey)
                                throw new ApplicationException("originalIdentityReference is PrimaryKey");
                            if (originalIdentityReference?.CheckExpectsAssignment() == true)
                                throw new ApplicationException("originalIdentityReference.CheckExpectsAssignment()");

                            OriginalIdentityReference = originalIdentityReference;

                            if (originalIdentityReference is EqualsOnly equalsOnly)
                                SetPublicKey(equalsOnly.PublicKey);
                        }

                        public TSorting AsOriginalBeforeSortingImplementedWith<TSorting>()
                            where TSorting : Alternate.Sorting
                            => AsOriginalBeforeSorting()?.ImplementedWith<TSorting>();

                        public Alternate.Sorting AsOriginalBeforeSorting()
                            => OriginalIdentityReference as Alternate.Sorting;

                        protected sealed override int CompareAfterAssignment(UniqueKey other)
                            => throw new NotSupportedException(nameof(WithoutExtraValues));
                    }

                    public class AfterAlternateSorting : PrimaryKey
                    {
                        public Alternate.Sorting AlternateSorting { get; private set; }

                        public void SetAlternateSorting(Alternate.Sorting alternateSorting)
                        {
                            EnsureExpectsAssignment();
                            AlternateSorting = alternateSorting;
                            if (CheckAllValuesWereAssigned()) ConfirmAssigned();
                        }

                        public override bool CheckAllValuesWereAssigned()
                            => base.CheckAllValuesWereAssigned() && CheckAlternateSortingIsAssigned();

                        public bool CheckAlternateSortingIsAssigned()
                            => AlternateSorting != null && !AlternateSorting.CheckExpectsAssignment();

                        protected override bool EqualsAfterAssignment(UniqueKey other)
                        {
                            var sorting = AlternateSorting ?? throw new ApplicationException("AlternateSorting == null");
                            bool primaryKeysEqual = base.EqualsAfterAssignment(other);
                            var otherSorting = other.AsAssignedBeforeSorting()
                                ?? other.AsAssignedAfterSorting()?.AlternateSorting;
                            if (!sorting.CanBeResolvedIntoPrivatePrimaryKey || otherSorting == null)
                                return primaryKeysEqual;

                            bool naturalKeysEqual = sorting.Equals(otherSorting);
                            if (naturalKeysEqual && !primaryKeysEqual) throw new ApplicationException("naturalKeysEqual && !primaryKeysEqual");
                            return primaryKeysEqual;
                        }

                        protected override int CompareAfterAssignment(UniqueKey other)
                        {
                            var sorting = AlternateSorting ?? throw new ApplicationException("AlternateSorting == null");
                            var otherSorting = other.AsAssignedBeforeSorting()
                                ?? other.AsAssignedAfterSorting()?.AlternateSorting
                                    ?? throw new ApplicationException("otherSorting == null");

                            int sortingCompare = sorting.CompareTo(otherSorting);
                            if (!sorting.PrefixedPrivatePrimaryKeySortingRequired) return sortingCompare;

                            var otherAfterSorting = other.AsAssignedAfterSorting()
                                ?? throw new ApplicationException("sorting.PrefixedPrivatePrimaryKeySortingRequired && other.AsAssignedAfterSorting() == null");
                            long privateKey = PrivateKey ?? throw new ApplicationException("!PrivateKey.HasValue");
                            long otherPrivateKey = otherAfterSorting.PrivateKey ?? throw new ApplicationException("!otherAfterSorting.PrivateKey.HasValue");

                            int privateKeyCompare = privateKey.CompareTo(otherPrivateKey);
                            if (sorting.PrefixedPrivatePrimaryKeySortingDescending) privateKeyCompare *= -1;
                            return sortingCompare != 0 ? sortingCompare : privateKeyCompare;
                        }

                        public override string ToString() => $"{base.ToString()} : {AlternateSorting?.ToString() ?? "N/A"}";
                    }
                }
            }
        }
    }
}