using System;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore.CollationAwareSorting
{
    internal readonly record struct EntityEntryModifyingPair<TEntity> where TEntity : class
    {
        internal EntityEntry<TEntity> LockedOrCreatedRecordData { get; }
        internal EntityEntry<TEntity> DetachedRecordDataForSettingChangedProperties { get; }

        internal EntityEntryModifyingPair(EntityEntry<TEntity> unchangedEntry, EntityEntry<TEntity> propertiesChangingEntry)
        {
            LockedOrCreatedRecordData = unchangedEntry ?? throw new ArgumentNullException(nameof(unchangedEntry));
            DetachedRecordDataForSettingChangedProperties = propertiesChangingEntry ?? throw new ArgumentNullException(nameof(propertiesChangingEntry));
            if (ReferenceEquals(unchangedEntry, propertiesChangingEntry))
                throw new ApplicationException("ReferenceEquals(unchangedEntry, propertiesChangingEntry)");
        }

        internal void ResolvePrivateKey(PrimaryKey primaryKey)
        {
            if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
            if (primaryKey.CheckPrivateKeyIsAssigned()) throw new ApplicationException("primaryKey.CheckPrivateKeyIsAssigned()");
            var changedEntry = LockedOrCreatedRecordData ?? throw new ApplicationException("LockedOrCreatedRecordData == null");
            var privateKey = changedEntry.GetNeverGeneratedSingleColumnBigintPrimaryKey().CurrentValue;
            if (privateKey <= 0) throw new ApplicationException("privateKey <= 0");
            primaryKey.SetPrivateKey(privateKey);
            if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("primaryKey.CheckExpectsAssignment()");
        }
    }
}