// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourCompany.Configuration.EFCore;

#nullable disable

namespace YourCompany.EFCore.Sqlite.YourCompanyDbContextConfigurationMigrations
{
    [DbContext(typeof(YourCompanyDbContext<YourCompanyDbContextConfiguration>))]
    partial class YourCompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("BINARY")
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Column2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Column4")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("examples_configuration_efcore_PK_Entity");

                    b.ToTable("examples_configuration_efcore_Entity");
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WithCrossCuttingFeatureData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("examples_configuration_efcore_PK_ReusableEntity");

                    b.ToTable("examples_configuration_efcore_ReusableEntity");
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeDataPutAwayForRareUseCases", "NonModularManualWayToMixIn", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Column1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column3")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column4")
                                .HasColumnType("TEXT");

                            b1.HasKey("EntityId")
                                .HasName("examples_configuration_efcore_PK_EntityMixin");

                            b1.ToTable("examples_configuration_efcore_EntityMixin");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_configuration_efcore_FK_EntityMixin_Entity_EntityId");
                        });

                    b.OwnsMany("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeOwnedCollection", "TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Column1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column3")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Column4")
                                .HasColumnType("TEXT");

                            b1.Property<int>("EntityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id")
                                .HasName("examples_configuration_efcore_PK_EntityOwnedCollection");

                            b1.HasIndex("EntityId")
                                .HasDatabaseName("examples_configuration_efcore_IX_EntityOwnedCollection_EntityId");

                            b1.ToTable("examples_configuration_efcore_EntityOwnedCollection");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_configuration_efcore_FK_EntityOwnedCollection_Entity_EntityId");
                        });

                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingToManuallyLinkEveryTime", "SomeReusableStuffLink", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReusableEntityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("EntityId")
                                .HasName("examples_configuration_efcore_PK_EntityLinkToReusableEntity");

                            b1.HasIndex("ReusableEntityId")
                                .HasDatabaseName("examples_configuration_efcore_IX_EntityLinkToReusableEntity_ReusableEntityId");

                            b1.ToTable("examples_configuration_efcore_EntityLinkToReusableEntity");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("examples_configuration_efcore_FK_EntityLinkToReusableEntity_Entity_EntityId");

                            b1.HasOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", null)
                                .WithMany()
                                .HasForeignKey("ReusableEntityId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("examples_configuration_efcore_FK_EntityLinkToReusableEntity_ReusableEntity_ReusableEntityId");
                        });

                    b.Navigation("NonModularManualWayToMixIn");

                    b.Navigation("SomeReusableStuffLink");

                    b.Navigation("TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt");
                });
#pragma warning restore 612, 618
        }
    }
}
