// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourCompany.Configuration.EFCore;

#nullable disable

namespace YourCompany.EFCore.PostgreSQL.CustomConfigurationMigrations
{
    [DbContext(typeof(YourCompanyDbContext<CustomConfiguration>))]
    [Migration("20260502222337_ItsAlive")]
    partial class ItsAlive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("C")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Column1")
                        .HasColumnType("integer");

                    b.Property<string>("Column2")
                        .HasColumnType("text");

                    b.Property<string>("Column3")
                        .HasColumnType("text");

                    b.Property<string>("Column4")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("e_con_e_h_m_r_PK_Entity");

                    b.ToTable("e_con_e_h_m_r_Entity");
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("WithCrossCuttingFeatureData")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("e_con_e_h_m_r_PK_ReusableEntity");

                    b.ToTable("e_con_e_h_m_r_ReusableEntity");
                });

            modelBuilder.Entity("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity", b =>
                {
                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeDataPutAwayForRareUseCases", "NonModularManualWayToMixIn", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<string>("Column1")
                                .HasColumnType("text");

                            b1.Property<string>("Column2")
                                .HasColumnType("text");

                            b1.Property<string>("Column3")
                                .HasColumnType("text");

                            b1.Property<string>("Column4")
                                .HasColumnType("text");

                            b1.HasKey("EntityId")
                                .HasName("e_con_e_h_m_r_PK_EntityMixin");

                            b1.ToTable("e_con_e_h_m_r_EntityMixin");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("e_con_e_h_m_r_FK_EntityMixin_Entity_EntityId");
                        });

                    b.OwnsMany("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingSomeOwnedCollection", "TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Column1")
                                .HasColumnType("text");

                            b1.Property<string>("Column2")
                                .HasColumnType("text");

                            b1.Property<string>("Column3")
                                .HasColumnType("text");

                            b1.Property<string>("Column4")
                                .HasColumnType("text");

                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.HasKey("Id")
                                .HasName("e_con_e_h_m_r_PK_EntityOwnedCollection");

                            b1.HasIndex("EntityId")
                                .HasDatabaseName("e_con_e_h_m_r_IX_EntityOwnedCollection_EntityId");

                            b1.ToTable("e_con_e_h_m_r_EntityOwnedCollection");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("e_con_e_h_m_r_FK_EntityOwnedCollection_Entity_EntityId");
                        });

                    b.OwnsOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+HavingToManuallyLinkEveryTime", "SomeReusableStuffLink", b1 =>
                        {
                            b1.Property<int>("EntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("ReusableEntityId")
                                .HasColumnType("integer");

                            b1.HasKey("EntityId")
                                .HasName("e_con_e_h_m_r_PK_EntityLinkToReusableEntity");

                            b1.HasIndex("ReusableEntityId")
                                .HasDatabaseName("e_con_e_h_m_r_IX_EntityLinkToReusableEntity_ReusableEntityId");

                            b1.ToTable("e_con_e_h_m_r_EntityLinkToReusableEntity");

                            b1.WithOwner()
                                .HasForeignKey("EntityId")
                                .HasConstraintName("e_con_e_h_m_r_FK_EntityLinkToReusableEntity_Entity_EntityId");

                            b1.HasOne("YourCompany.EFCore.NeverPretendingToBeYourDomainModel.EFCoreConventionalEntity+SomeReusableEntityHereForBrevity", null)
                                .WithMany()
                                .HasForeignKey("ReusableEntityId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("e_con_e_h_m_r_FK_EntityLinkToReusableEntity_ReusableEntiCB4546B");
                        });

                    b.Navigation("NonModularManualWayToMixIn");

                    b.Navigation("SomeReusableStuffLink");

                    b.Navigation("TypicallyAlwaysIncludedCollectionIfYouAreGoingToBuildAggregatesOnTopOfIt");
                });
#pragma warning restore 612, 618
        }
    }
}
