<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YourCompany.OLTP.RecordsManagement.Persistence\YourCompany.OLTP.RecordsManagement.Persistence.csproj" />
  </ItemGroup>

</Project>
