<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>1b194502-7a41-4075-a5b5-c22033def7eb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YourCompany.Dapper\YourCompany.Dapper.csproj" />
    <ProjectReference Include="..\YourCompany.Dapper.PostgreSQL\YourCompany.Dapper.PostgreSQL.csproj" />
  </ItemGroup>

</Project>