using System;

namespace YourCompany.OLTP.StateOwnership.Reflection.EFCore
{
    public class DelegatedPrimaryKeyGenerationTable
    {
        public const string EntityTableNameSuffix = "_PublicKeys";
        public long AutoGeneratedPrimaryKey { get; set; }
        public Guid PublicKey { get; set; }
    }
}