using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YourCompany.OLTP.StateOwnership.Reflection.EFCore
{
    public static partial class MetadataHelper
    {
        public const string RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName = "Id";

        public static PropertyBuilder<long> DeclareRecordDataDelegatedBigintPrimaryKeyGeneratedProperty(
            this ModelBuilder modelBuilder, Type recordDataImplementingType)
        {
            if (recordDataImplementingType == null) throw new ArgumentNullException(nameof(recordDataImplementingType));
            var entityType = modelBuilder.Entity(recordDataImplementingType);
            string entityTableName = entityType.Metadata.GetTableName() ?? throw new ApplicationException("tableName == null");

            var property = entityType
                .Property<long>(RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName)
                .ValueGeneratedNever();

            entityType.HasKey(RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName);
            string publicKeysTableName = entityTableName + DelegatedPrimaryKeyGenerationTable.EntityTableNameSuffix;
            modelBuilder.SharedTypeEntity<DelegatedPrimaryKeyGenerationTable>(publicKeysTableName, publicKeyEntity =>
            {
                publicKeyEntity.ToTable(publicKeysTableName);
                publicKeyEntity.Property(id => id.AutoGeneratedPrimaryKey).ValueGeneratedOnAdd();
                publicKeyEntity.HasKey(id => id.AutoGeneratedPrimaryKey);
                publicKeyEntity.Property(id => id.PublicKey).ValueGeneratedNever();
                publicKeyEntity.HasIndex(id => id.PublicKey).IsUnique();
                publicKeyEntity.HasOne(entityType.Metadata.ClrType, null)
                    .WithOne()
                    .HasForeignKey(entityType.Metadata.ClrType, RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName)
                    .OnDelete(DeleteBehavior.Restrict);
            });
            return property;
        }

        public static IReadOnlyProperty GetRecordDataNeverGeneratedBigintPrimaryKeyProperty(
            this IReadOnlyEntityType entityType)
        {
            var primaryKey = entityType.FindPrimaryKey() ?? throw new ApplicationException("primaryKey == null");
            if (!primaryKey.Properties[0].CheckIsNeverGeneratedSingleColumnBigintPrimaryKey())
                throw new ApplicationException("!primaryKey.Properties[0].CheckIsNeverGeneratedSingleColumnBigintPrimaryKey()");

            if (!entityType.GetForeignKeys().Any(fk => fk.Properties.Count == 1 && fk.Properties[0] == primaryKey))
                throw new ApplicationException("!entityType.GetForeignKeys().Any(fk => fk.Properties.Count == 1 && fk.Properties[0] == primaryKey)");

            return primaryKey.Properties[0];
        }

        public static IReadOnlyForeignKey GetIdentityGeneratingEntityForeignKey(
            this IReadOnlyProperty neverGeneratedBigintPrimaryKey)
        {
            if (!neverGeneratedBigintPrimaryKey.CheckIsNeverGeneratedSingleColumnBigintPrimaryKey()) throw new ApplicationException("!neverGeneratedBigintPrimaryKey.CheckIsNeverGeneratedSingleColumnBigintPrimaryKey()");
            var entityType = (IReadOnlyEntityType)neverGeneratedBigintPrimaryKey.DeclaringType ?? throw new ApplicationException("neverGeneratedBigintPrimaryKey.DeclaringType == null");
            return entityType.GetForeignKeys().Single(fk => fk.Properties.Count == 1 && fk.Properties[0] == neverGeneratedBigintPrimaryKey);
        }

        public static PropertyEntry<TEntity, long> GetNeverGeneratedSingleColumnBigintPrimaryKey<TEntity>(
            this EntityEntry<TEntity> entry)
            where TEntity : class
        {
            var property = entry.Property<long>(RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName);
            if (!property.Metadata.CheckIsNeverGeneratedSingleColumnBigintPrimaryKey())
                throw new ApplicationException("!property.Metadata.CheckIsNeverGeneratedSingleColumnBigintPrimaryKey()");
            return property;
        }

        public static bool CheckIsNeverGeneratedSingleColumnBigintPrimaryKey(this IReadOnlyProperty property)
            => property.Name == RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName
            && property.ClrType == typeof(long)
            && property.ValueGenerated == ValueGenerated.Never
            && property.FindContainingPrimaryKey()?.Properties.Count == 1;
    }
}