<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\YourCompany.OLTP.RecordsManagement.DI.EFCore\YourCompany.OLTP.RecordsManagement.DI.EFCore.csproj" />
  </ItemGroup>

</Project>
