<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\YourCompany.Configuration.EFCore.Hosting\YourCompany.Configuration.EFCore.Hosting.csproj" />
  </ItemGroup>

</Project>
