// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourCompany.EFCore.Sqlite.YourCompanyDbContextConfigurationMigrations;

#nullable disable

namespace YourCompany.EFCore.Sqlite.YourCompanyDbContextConfigurationMigrations.KickStartMigrations
{
    [DbContext(typeof(KickStartDbContext))]
    [Migration("20260502102939_InitMigrations")]
    partial class InitMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
#pragma warning restore 612, 618
        }
    }
}
