using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        public abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            public abstract partial class WithoutIds : SingleEntityQuery<TRecordData, TQueryableRecordData>,
                RecordsDataAccess.IFilterBeforeRead
            {
                private IQueryable<TQueryableRecordData> _queryable;

                private WithoutIds(YourCompanyDbContext<TConfiguration> context) : base(context) { }

                bool RecordsDataAccess.IFilterBeforeRead.FilterAfterSorting(object specification)
                    => FilterAfterSortingWithoutIdsBeforeRead(specification);

                protected override bool FilterAfterSortingWithoutIdsBeforeRead(object specification)
                {
                    if (specification == null) throw new ArgumentNullException(nameof(specification));
                    EnsureNoContextLock();
                    EnsureBeforeResolvingWithoutIds();

                    var builder = _context.GetQueryBuilderForSpecification<TRecordData, TQueryableRecordData>(specification);
                    if (builder == null) return false;
                    if (builder is not RecordDataQueryBuilder.ForSingleRecordData<TRecordData> typed)
                        throw new ApplicationException("builder is not RecordDataQueryBuilder.ForSingleRecordData<TRecordData> typed");

                    var predicate = typed.Filter<TQueryableRecordData>(specification);
                    if (predicate == null) return false;

                    var queryable = _queryable ??= Query() ?? throw new ApplicationException("Query() == null");
                    _queryable = queryable.Where(predicate);
                    return true;
                }

                protected override async Task<IReadOnlyList<long>> ResolvePrimaryKeys(
                    int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                {
                    if (PrimaryKeys != null) throw new ApplicationException("PrimaryKeys != null");
                    EnsureReadingForReadOnlyOrByModifyingWrapperOnly();
                    EnsureBeforeResolvingWithoutIds();
                    _queryable ??= Query() ?? throw new ApplicationException("Query() == null");
                    var batched = _queryable.Skip(batchSize).Take(recordsCountToSkip);
                    var readPrimaryKeys = await _context.GetPrimaryKeys<TRecordData, TQueryableRecordData>(
                        batched, cancellationToken);
                    var existingRecordPrivateKeys = readPrimaryKeys.Count > 0 ? new long[readPrimaryKeys.Count] : null;
                    ResolvePrimaryKeys(readPrimaryKeys, existingRecordPrivateKeys);
                    if (PrimaryKeys == null) throw new ApplicationException("PrimaryKeys == null");
                    if (PrimaryKeys.Count != readPrimaryKeys.Count) throw new ApplicationException("PrimaryKeys.Count != readPrimaryKeys.Count");
                    if (existingRecordPrivateKeys != null && existingRecordPrivateKeys.Length != readPrimaryKeys.Count)
                        throw new ApplicationException("existingRecordPrivateKeys != null && existingRecordPrivateKeys.Length != readPrimaryKeys.Count");
                    return existingRecordPrivateKeys;
                }

                protected abstract IQueryable<TQueryableRecordData> Query();

                protected abstract void ResolvePrimaryKeys(
                    IReadOnlyList<RecordDataQueries.PrimaryKeyWithExists> readPrimaryKeys,
                    long[] existingRecordPrivateKeys);

                protected override bool CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData(
                    int recordIndex,
                    PrimaryKey possiblyMissing)
                {
                    if (possiblyMissing == null) throw new ApplicationException("possiblyMissing == null");
                    if (possiblyMissing.CheckExpectsAssignment()) throw new ApplicationException("possiblyMissing.CheckExpectsAssignment()");
                    return false;
                }

                protected static void ResolvePrimaryKeys(
                    IReadOnlyList<RecordDataQueries.PrimaryKeyWithExists> readPrimaryKeys,
                    PrimaryKey.WithoutExtraValues[] primaryKeys,
                    long[] existingRecordPrivateKeys)
                {
                    if (readPrimaryKeys == null) throw new ArgumentNullException(nameof(readPrimaryKeys));
                    if (primaryKeys == null) throw new ArgumentNullException(nameof(primaryKeys));
                    if (readPrimaryKeys.Count != primaryKeys.Length) throw new ApplicationException("readPrimaryKeys.Count != primaryKeys.Length");

                    for (int i = 0; i < readPrimaryKeys.Count; i++)
                    {
                        var readPrimaryKey = readPrimaryKeys[i];
                        if (!readPrimaryKey.RecordDataExists) throw new ApplicationException("!readPrimaryKey.RecordDataExists");
                        var primaryKey = new PrimaryKey.WithoutExtraValues();
                        primaryKey.SetPublicKey(readPrimaryKey.PublicKey);
                        primaryKey.SetPrivateKey(readPrimaryKey.PrivateKey);
                        if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("primaryKey.CheckExpectsAssignment()");
                        primaryKeys[i] = primaryKey;
                        if (existingRecordPrivateKeys == null) throw new ApplicationException("existingRecordPrivateKeys == null");
                        existingRecordPrivateKeys[i] = readPrimaryKey.PrivateKey;
                    }
                }

                protected static void ResolvePrimaryKeys(
                    IReadOnlyList<RecordDataQueries.PrimaryKeyWithExists> readPrimaryKeys,
                    PrimaryKey.AfterAlternateSorting[] primaryKeys,
                    long[] existingRecordPrivateKeys)
                {
                    if (readPrimaryKeys == null) throw new ArgumentNullException(nameof(readPrimaryKeys));
                    if (primaryKeys == null) throw new ArgumentNullException(nameof(primaryKeys));
                    if (readPrimaryKeys.Count != primaryKeys.Length) throw new ApplicationException("readPrimaryKeys.Count != primaryKeys.Length");

                    for (int i = 0; i < readPrimaryKeys.Count; i++)
                    {
                        var readPrimaryKey = readPrimaryKeys[i];
                        if (!readPrimaryKey.RecordDataExists) throw new ApplicationException("!readPrimaryKey.RecordDataExists");
                        var primaryKey = new PrimaryKey.AfterAlternateSorting();
                        primaryKey.SetPublicKey(readPrimaryKey.PublicKey);
                        primaryKey.SetPrivateKey(readPrimaryKey.PrivateKey);
                        if (!primaryKey.CheckExpectsAssignment()) throw new ApplicationException("!primaryKey.CheckExpectsAssignment()");
                        primaryKeys[i] = primaryKey;
                        if (existingRecordPrivateKeys == null) throw new ApplicationException("existingRecordPrivateKeys == null");
                        existingRecordPrivateKeys[i] = readPrimaryKey.PrivateKey;
                    }
                }

                protected void EnsureBeforeResolvingWithoutIds()
                {
                    if (PrimaryKeys != null) throw new ApplicationException("PrimaryKeys != null");
                    if (_primaryKeysWithRecordDataByPrivateKey != null) throw new ApplicationException("_primaryKeysWithRecordDataByPrivateKey != null");
                }

                protected void EnsureAfterReadWithoutIds()
                {
                    if (_queryable == null) throw new ApplicationException("_queryable == null");
                    if (PrimaryKeys == null) throw new ApplicationException("PrimaryKeys != null");
                }
            }
        }
    }
}