using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.OLTP.StateOwnership;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    internal abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        internal abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            internal partial class ReadBeforeModifying<TPrimaryKey> : SingleEntityQuery<TRecordData, TQueryableRecordData>,
                RecordsDataAccess.IReadBeforeModifying<TPrimaryKey>,
                RecordsDataAccess.IReadBeforeModifyingIdentity<TPrimaryKey>
                where TPrimaryKey : PrimaryKey
            {
                private readonly SingleEntityQuery<TRecordData, TQueryableRecordData> _reader;
                private readonly RecordsDataAccess.IReadBeforeModifying _readBeforeModifying;
                private readonly RecordsDataAccess.IFinish _finishNext;

                internal override IReadOnlyList<PrimaryKey> PrimaryKeys => _reader.PrimaryKeys;

                internal ReadBeforeModifying(
                    SingleEntityQuery<TRecordData, TQueryableRecordData> reader,
                    RecordsDataAccess.IReadBeforeModifying readBeforeModifying,
                    RecordsDataAccess.IFinish finishNext)
                    : base(reader._context)
                {
                    _reader = reader ?? throw new ArgumentNullException(nameof(reader));
                    _readBeforeModifying = readBeforeModifying ?? throw new ArgumentNullException(nameof(readBeforeModifying));
                    _finishNext = finishNext ?? throw new ArgumentNullException(nameof(finishNext));
                }

                bool RecordsDataAccess.IAllowAtomicUpdateWithUnchangedRecordsDataRead.ChangeEachRecordToMatch(object specification)
                    => ChangeEachRecordToMatchWithoutIdsBeforeRead(specification);

                protected bool ChangeEachRecordToMatchWithoutIdsBeforeRead(object specification)
                {
                    if (specification == null) throw new ArgumentNullException(nameof(specification));
                    EnsureNoContextLockModifyingOnly();
                    if (_reader.PrimaryKeys != null) throw new ApplicationException("_reader.PrimaryKeys != null");
                    EnsureBeforeRead();
                    var queryBuilder = _context.GetQueryBuilderForSpecification<TRecordData, TQueryableRecordData>(
                        specification);
                    if (queryBuilder != null)
                        EntityEntryModifyingVisitor.AddEachRecordModifyingSpecification(specification, queryBuilder);
                    return queryBuilder != null;
                }

                Task<int> RecordsDataAccess.IReadBeforeModifying.ReadAndLockForChangesPersisting(
                    int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                    => _readBeforeModifying.ReadAndLockForChangesPersisting(batchSize, recordsCountToSkip, cancellationToken);

                internal override async Task<int> ReadAndLockForChangesPersisting(
                    int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                {
                    EnsureContextLockedModifyingOnly();
                    EnsureCurrentTransaction();
                    EnsureBeforeRead();
                    await _reader.ReadAndLockForChangesPersisting(batchSize, recordsCountToSkip, cancellationToken);
                    EnsureAfterReadBeforePopulatingEntries();
                    PopulateModifyingEntriesAfterRead();
                    EnsureApplyingChanges();
                    return _reader.PrimaryKeys.Count;
                }

                protected sealed override Task<IReadOnlyList<long>> ResolvePrimaryKeys(
                    int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
                    => throw new ApplicationException(nameof(ResolvePrimaryKeys));

                protected sealed override Task ReadRecordDataByPrivateKeys(
                    IReadOnlyList<long> existingRecordPrivateKeys, bool lockAndTrack, CancellationToken cancellationToken)
                    => throw new ApplicationException(nameof(ReadRecordDataByPrivateKeys));

                protected sealed override bool CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData(
                    int recordIndex, PrimaryKey possiblyMissing)
                    => throw new ApplicationException(nameof(CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData));

                protected sealed override void EnsurePrimaryKeyIsAssignedWithExistingRecordsData(
                    long privateKey,
                    PrimaryKey primaryKey,
                    RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData> record)
                    => throw new ApplicationException(nameof(EnsurePrimaryKeyIsAssignedWithExistingRecordsData));

                RecordsDataAccess.IReadBeforeModifyingIdentity<TPrimaryKey>
                    RecordsDataAccess.IReadBeforeModifying<TPrimaryKey>.Next => this;

                public TPrimaryKey GetReadRecordIdentity(int recordIndex, Identity originalIdentityWhenByIds)
                {
                    EnsureNoContextLockModifyingOnly();
                    EnsureApplyingChanges();
                    return (TPrimaryKey)_reader.PrimaryKeys[recordIndex];
                }

                RecordsDataAccess.IModifying RecordsDataAccess.IReadBeforeModifyingIdentity<TPrimaryKey>.Next => this;

                RecordsDataAccess.IFinish RecordsDataAccess.IReadIdentity<TPrimaryKey>.Next
                    => throw new ApplicationException("RecordsDataAccess.IReadIdentity<TPrimaryKey>.Next");

                RecordsDataAccess.IFinish RecordsDataAccess.IModifying.Next => _finishNext;

                protected void EnsureContextLockedModifyingOnly()
                {
                    EnsureContextLocked();
                    EnsureModifying();
                }

                protected void EnsureNoContextLockModifyingOnly()
                {
                    EnsureNoContextLock();
                    EnsureModifying();
                }

                protected void EnsureAfterReadBeforePopulatingEntries()
                {
                    EnsureAfterRead();
                    if (_modifyingEntries != null) throw new ApplicationException("_modifyingEntries != null");
                    if (ChangesApplied) throw new ApplicationException("ChangesApplied");
                }

                protected void EnsureApplyingChanges()
                {
                    EnsureAfterPopulatingEntries();
                    if (ChangesApplied) throw new ApplicationException("ChangesApplied");
                }

                protected void EnsureAfterPopulatingEntries()
                {
                    EnsureAfterRead();
                    if (_modifyingEntries == null) throw new ApplicationException("_modifyingEntries == null");
                }

                protected void EnsureBeforeRead()
                {
                    EnsureModifying();
                    if (_modifyingEntries != null) throw new ApplicationException("_modifyingEntries != null");
                    if (ChangesApplied) throw new ApplicationException("ChangesApplied");
                }

                protected void EnsureAfterRead()
                {
                    EnsureCurrentTransaction();
                    if (_reader.PrimaryKeys == null) throw new ApplicationException("_reader.PrimaryKeys == null");
                }

                protected void EnsureCurrentTransaction()
                {
                    EnsureModifying();
                    if (_context.Database.CurrentTransaction == null) throw new ApplicationException("_context.Database.CurrentTransaction == null");
                }
            }
        }
    }
}