using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public partial class YourCompanyDbContext<TConfiguration>
    {
        public Task<List<RecordDataQueries.PrimaryKeyWithExists>> GetPrimaryKeys<TRecordData, TQueryableRecordData>(
            IEnumerable<Guid> publicKeys, CancellationToken cancellationToken)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (publicKeys == null) throw new ArgumentNullException(nameof(publicKeys));
            EnsureLocked();
            return DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>()
                .Where(primaryKey => publicKeys.Contains(primaryKey.PublicKey))
                .GroupJoin(
                    Set<TQueryableRecordData>(),
                    primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                    entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                    (primaryKey, singleEntityGroup) => new { PrimaryKey = primaryKey, SingleEntityGroup = singleEntityGroup })
                .SelectMany(
                    g => g.SingleEntityGroup.DefaultIfEmpty(),
                    (g, entity) => new
                    {
                        g.PrimaryKey,
                        Entity = entity
                    })
                .AsNoTracking()
                .Select(x => new RecordDataQueries.PrimaryKeyWithExists
                {
                    PublicKey = x.PrimaryKey.PublicKey,
                    PrivateKey = x.PrimaryKey.AutoGeneratedPrimaryKey,
                    RecordDataExists = x.Entity != null
                })
                .ToListAsync(cancellationToken);
        }

        public List<RecordDataQueries.PrimaryKeyWithExists>
            GetPrimaryKeysLocal<TRecordData, TQueryableRecordData>(IEnumerable<Guid> publicKeys)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (publicKeys == null) throw new ArgumentNullException(nameof(publicKeys));
            EnsureLocked();
            return DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>().Local
                .Where(primaryKey => publicKeys.Contains(primaryKey.PublicKey))
                .GroupJoin(
                    Set<TQueryableRecordData>().Local,
                    primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                    entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                    (primaryKey, singleEntityGroup) => new { PrimaryKey = primaryKey, SingleEntityGroup = singleEntityGroup })
                .SelectMany(
                    g => g.SingleEntityGroup.DefaultIfEmpty(),
                    (g, entity) => new
                    {
                        g.PrimaryKey,
                        Entity = entity
                    })
                .Select(x => new RecordDataQueries.PrimaryKeyWithExists
                {
                    PublicKey = x.PrimaryKey.PublicKey,
                    PrivateKey = x.PrimaryKey.AutoGeneratedPrimaryKey,
                    RecordDataExists = x.Entity != null
                })
                .ToList();
        }

        public Task<List<RecordDataQueries.PrimaryKeyWithExists>> GetPrimaryKeys<TRecordData, TQueryableRecordData>(
            IQueryable<TQueryableRecordData> queryable,
            CancellationToken cancellationToken)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (queryable == null) throw new ArgumentNullException(nameof(queryable));
            EnsureLocked();
            return queryable.AsNoTracking().Join(
                DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>(),
                entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                (_, primaryKey) => new RecordDataQueries.PrimaryKeyWithExists
                {
                    PublicKey = primaryKey.PublicKey,
                    PrivateKey = primaryKey.AutoGeneratedPrimaryKey,
                    RecordDataExists = true
                })
                .ToListAsync(cancellationToken);
        }

        public Task<Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>>
            GetPrimaryKeysWithRecordDataToDictionary<TRecordData, TQueryableRecordData>(
                IReadOnlyList<long> privateKeys,
                CancellationToken cancellationToken)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (privateKeys == null) throw new ArgumentNullException(nameof(privateKeys));
            EnsureLocked();
            return Set<TQueryableRecordData>().AsNoTracking().Join(
                DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>(),
                entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                (entity, primaryKey) => new RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>
                {
                    PublicKey = primaryKey.PublicKey,
                    PrivateKey = primaryKey.AutoGeneratedPrimaryKey,
                    RecordData = entity
                })
                .Where(p => privateKeys.Contains(p.PrivateKey))
                .ToDictionaryAsync(p => p.PrivateKey, cancellationToken);
        }

        public Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>
            GetPrimaryKeysWithLocalRecordDataToDictionary<TRecordData, TQueryableRecordData>(
                IReadOnlyList<long> privateKeys)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (privateKeys == null) throw new ArgumentNullException(nameof(privateKeys));
            EnsureLocked();

            var query = Set<TQueryableRecordData>().Local.Join(
                DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>().Local,
                entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                (entity, primaryKey) => new RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>
                {
                    PublicKey = primaryKey.PublicKey,
                    PrivateKey = primaryKey.AutoGeneratedPrimaryKey,
                    RecordData = entity
                })
                .Where(p => privateKeys.Contains(p.PrivateKey));

            Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>> result = null;

            foreach (var record in query)
            {
                result ??= new Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>();
                result.Add(record.PrivateKey, record);
            }

            return result;
        }

        public DbSet<DelegatedPrimaryKeyGenerationTable>
            DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>()
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            var queryableRecordDataType = GetQueryableRecordDataType(typeof(TRecordData));
            if (queryableRecordDataType != typeof(TQueryableRecordData)) throw new ApplicationException("queryableRecordDataType != typeof(TQueryableRecordData)");
            string tableName = Model.FindEntityType(queryableRecordDataType)?.GetTableName() ?? throw new ApplicationException("tableName == null");
            return Set<DelegatedPrimaryKeyGenerationTable>(
                name: tableName + DelegatedPrimaryKeyGenerationTable.EntityTableNameSuffix);
        }

        protected virtual void DeclarePrimaryKey(
            ModelBuilder modelBuilder, Type recordDataType, Type queryableRecordDataType)
            => modelBuilder.DeclareRecordDataDelegatedBigintPrimaryKeyGeneratedProperty(queryableRecordDataType);
    }
}