using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore.CollationAwareSorting;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;
using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    internal abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        internal abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            internal partial class ReadBeforeModifying<TPrimaryKey> : RecordsDataAccess.IModifying
            {
                private EntityEntryModifyingPair<TQueryableRecordData>[] _modifyingEntries;
                private EntityEntryModifyingVisitor<TRecordData, TQueryableRecordData> _entityEntryModifyingVisitor;

                internal virtual EntityEntryModifyingVisitor<TRecordData, TQueryableRecordData> EntityEntryModifyingVisitor
                    => _entityEntryModifyingVisitor
                        ??= new EntityEntryModifyingVisitor<TRecordData, TQueryableRecordData>(
                            YourCompanyDbContext<TConfiguration>.SingleRuntimeCollationAwareSortingModelProviderPerConfigurationType);

                protected bool ChangesApplied { get; private set; }

                protected void PopulateModifyingEntriesAfterRead()
                {
                    EnsureContextLockedModifyingOnly();
                    EnsureAfterReadBeforePopulatingEntries();

                    _modifyingEntries = new EntityEntryModifyingPair<TQueryableRecordData>[_reader.PrimaryKeys.Count];
                    for (int recordIndex = 0; recordIndex < _reader.PrimaryKeys.Count; recordIndex++)
                    {
                        var primaryKey = _reader.PrimaryKeys[recordIndex];
                        if (primaryKey == null) continue;
                        var lockedRecordDataWithoutChanges = (TQueryableRecordData)_reader.GetRecordDataAfterAccess(recordIndex, primaryKey);
                        _modifyingEntries[recordIndex] = PopulateModifyingEntriesAfterRead(recordIndex, primaryKey, lockedRecordDataWithoutChanges);
                    }
                }

                protected EntityEntryModifyingPair<TQueryableRecordData> PopulateModifyingEntriesAfterRead(
                    int recordDataIndex, PrimaryKey primaryKey, TQueryableRecordData lockedRecordDataWithoutChanges)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    EnsureContextLockedModifyingOnly();
                    EnsureAfterReadBeforePopulatingEntries();

                    var unchangedEntry = lockedRecordDataWithoutChanges != null
                        ? _context.Entry(lockedRecordDataWithoutChanges)
                        : _context.Entry(Activator.CreateInstance<TQueryableRecordData>());
                    var propertiesChangingEntry = _context.Entry(Activator.CreateInstance<TQueryableRecordData>());

                    if (lockedRecordDataWithoutChanges == null)
                    {
                        AttachCreatedRecord(recordDataIndex, primaryKey, unchangedEntry);
                        SetSortingKeyPropertiesToCreatedRecord(primaryKey, propertiesChangingEntry);
                    }

                    _context.SetExplicitLastModifiedAtPropertyIfUnset<TRecordData, TQueryableRecordData>(
                        propertiesChangingEntry);

                    if (unchangedEntry.State != EntityState.Unchanged) throw new ApplicationException("unchangedEntry.State != EntityState.Unchanged");
                    if (propertiesChangingEntry.State != EntityState.Detached) throw new ApplicationException("propertiesChangingEntry.State != EntityState.Detached");

                    return new EntityEntryModifyingPair<TQueryableRecordData>(unchangedEntry, propertiesChangingEntry);
                }

                protected void AttachCreatedRecord(
                    int recordDataIndex, PrimaryKey primaryKey, EntityEntry<TQueryableRecordData> unchangedEntry)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    if (unchangedEntry == null) throw new ArgumentNullException(nameof(unchangedEntry));
                    if (unchangedEntry.State != EntityState.Detached) throw new ApplicationException("unchangedEntry.State != EntityState.Detached");
                    EnsureContextLockedModifyingOnly();
                    EnsureAfterReadBeforePopulatingEntries();

                    var generatedPrivateKeyProperty = GeneratePrivateKey(recordDataIndex, primaryKey)
                        ?? throw new ApplicationException("GeneratePrivateKey(i, primaryKey) == null");

                    var privateKeyProperty = unchangedEntry.GetNeverGeneratedSingleColumnBigintPrimaryKey();
                    if (privateKeyProperty.CurrentValue != 0) throw new ApplicationException("privateKeyProperty.CurrentValue != 0");
                    privateKeyProperty.CurrentValue = generatedPrivateKeyProperty.CurrentValue;

                    unchangedEntry.State = EntityState.Unchanged;
                }

                protected PropertyEntry<DelegatedPrimaryKeyGenerationTable, long> GeneratePrivateKey(
                    int recordIndex, PrimaryKey primaryKey)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    EnsureContextLockedModifyingOnly();
                    EnsureAfterReadBeforePopulatingEntries();
                    if (_reader.GetRecordDataAfterAccess(recordIndex, primaryKey) != null)
                        throw new ApplicationException("_reader.GetRecordDataAfterAccess(recordIndex, primaryKey) != null");

                    return !primaryKey.CheckPrivateKeyIsAssigned()
                        ? _context.GeneratePrimaryKey<TRecordData, TQueryableRecordData>(primaryKey)
                        : _reader.CheckResolvedFromPublicKeyMissingRecordData(recordIndex, primaryKey)
                            ? _context.AttachExistingPrimaryKeyWithMissingRecordData<TRecordData, TQueryableRecordData>(primaryKey)
                            : throw new ApplicationException("primaryKey.CheckPrivateKeyIsAssigned() && !_reader.CheckResolvedFromPublicKeyMissingRecordData(recordIndex, primaryKey)");
                }

                public object CreateRecordDataForSettingChangedProperties(int recordIndex, PrimaryKey primaryKey)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    EnsureNoContextLockModifyingOnly();
                    EnsureApplyingChanges();
                    _reader.EnsureMatchingResolvedPrimaryKey(recordIndex, primaryKey);
                    var entry = _modifyingEntries[recordIndex].DetachedRecordDataForSettingChangedProperties
                        ?? throw new ApplicationException("_modifyingEntries[recordIndex].DetachedRecordDataForSettingChangedProperties == null");
                    if (entry.State != EntityState.Detached) throw new ApplicationException("entry.State != EntityState.Detached");
                    return entry.Entity;
                }

                public bool ChangeSpecifiedRecordToMatch(int recordIndex, PrimaryKey primaryKey, object specification)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    if (specification == null) throw new ArgumentNullException(nameof(specification));
                    EnsureNoContextLockModifyingOnly();
                    EnsureApplyingChanges();
                    _reader.EnsureMatchingResolvedPrimaryKey(recordIndex, primaryKey);
                    var queryBuilder = _context.GetQueryBuilderForSpecification<TRecordData, TQueryableRecordData>(
                        specification);
                    if (queryBuilder != null)
                        EntityEntryModifyingVisitor.AddSpecifiedRecordModifyingSpecification(
                            recordIndex, specification, queryBuilder);
                    return queryBuilder != null;
                }

                public Task PersistChanges(CancellationToken cancellationToken)
                {
                    EnsureNoContextLockModifyingOnly();
                    EnsureApplyingChanges();
                    return Task.CompletedTask;
                }

                public object GetLockedRecordDataWithoutChanges(int recordIndex, PrimaryKey primaryKey)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    EnsureNoContextLockModifyingOnly();
                    EnsureApplyingChanges();
                    _reader.EnsureMatchingResolvedPrimaryKey(recordIndex, primaryKey);
                    var entry = _modifyingEntries[recordIndex].LockedOrCreatedRecordData
                        ?? throw new ApplicationException("_modifyingEntries[recordIndex].LockedOrCreatedRecordData == null");
                    if (entry.State != EntityState.Unchanged) throw new ApplicationException("entry.State != EntityState.Unchanged");
                    return entry.Entity;
                }
            }
        }
    }
}