using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    internal abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
    {
        internal abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
        {
            internal abstract partial class ByIds
            {
                private HashSet<object> _primaryKeysResolvedFromPublicKeyMissingRecordDataByReference;

                protected virtual async Task ResolvePrivateKeys(
                    Dictionary<Guid, int> indeciesByPublicKey, CancellationToken cancellationToken)
                {
                    if (indeciesByPublicKey == null) throw new ArgumentNullException(nameof(indeciesByPublicKey));
                    if (indeciesByPublicKey.Count == 0) throw new ApplicationException("indeciesByPublicKey.Count == 0");
                    EnsureReadingForReadOnlyOrByModifyingWrapperOnly();
                    if (_primaryKeysWithRecordDataByPrivateKey != null) throw new ApplicationException("_primaryKeysWithRecordDataByPrivateKey != null");

                    var alreadyLockedPrimaryKeys = _context.GetPrimaryKeysLocal<TRecordData, TQueryableRecordData>(
                        indeciesByPublicKey.Keys);
                    if (alreadyLockedPrimaryKeys.Count > 0 && _context.Database.CurrentTransaction == null)
                        throw new ApplicationException("alreadyLockedPrimaryKeys.Count > 0 && _context.Database.CurrentTransaction == null");

                    for (int i = 0; i < alreadyLockedPrimaryKeys.Count; i++)
                        ResolveLocalOrQueriedPrivateKey(alreadyLockedPrimaryKeys[i], indeciesByPublicKey);

                    if (indeciesByPublicKey.Count > 0)
                    {
                        var queriedPrimaryKeys = await _context.GetPrimaryKeys<TRecordData, TQueryableRecordData>(
                            indeciesByPublicKey.Keys, cancellationToken);
                        for (int i = 0; i < queriedPrimaryKeys.Count; i++)
                            ResolveLocalOrQueriedPrivateKey(queriedPrimaryKeys[i], indeciesByPublicKey);
                    }

                    if (indeciesByPublicKey.Count > 0)
                    {
                        if (ReadOnly && !SkipMissing) throw new ApplicationException("indeciesByPublicKey.Count > 0 && ReadOnly && !SkipMissing)");
                        if (SkipMissing)
                            foreach (var kvp in indeciesByPublicKey)
                                SkipMissingRecord(kvp.Value);
                        indeciesByPublicKey.Clear();
                    }
                }

                protected virtual void ResolveLocalOrQueriedPrivateKey(
                    RecordDataQueries.PrimaryKeyWithExists primaryKey, Dictionary<Guid, int> indeciesByPublicKey)
                {
                    if (indeciesByPublicKey == null) throw new ArgumentNullException(nameof(indeciesByPublicKey));
                    if (indeciesByPublicKey.Count == 0) throw new ApplicationException("indeciesByPublicKey.Count == 0");
                    EnsureReadingForReadOnlyOrByModifyingWrapperOnly();
                    if (_primaryKeysWithRecordDataByPrivateKey != null) throw new ApplicationException("_primaryKeysWithRecordDataByPrivateKey != null");

                    if (!indeciesByPublicKey.Remove(primaryKey.PublicKey, out var primaryKeyIndex))
                        throw new ApplicationException("!indeciesByPublicKey.Remove(primaryKey.PublicKey, out var primaryKeyIndex)");

                    var resolvedPrimaryKey = PrimaryKeys[primaryKeyIndex];
                    if (resolvedPrimaryKey == null)
                    {
                        if (!SkipMissing) throw new ApplicationException("!SkipMissing");
                        return;
                    }

                    if (resolvedPrimaryKey.CheckExpectsAssignment())
                    {
                        resolvedPrimaryKey.SetPrivateKey(primaryKey.PrivateKey);
                        if (resolvedPrimaryKey.CheckExpectsAssignment()) throw new ApplicationException("resolvedPrimaryKey.CheckExpectsAssignment()");
                    }
                    else
                    {
                        long resolvedPrivateKey = resolvedPrimaryKey.PrivateKey ?? throw new ApplicationException("!resolvedPrimaryKey.PrivateKey.HasValue");
                        if (resolvedPrivateKey != primaryKey.PrivateKey) throw new ApplicationException("resolvedPrivateKey != primaryKey.PrivateKey");
                    }

                    if (!resolvedPrimaryKey.CheckExpectsAssignment()) throw new ApplicationException("!resolvedPrimaryKey.CheckExpectsAssignment()");

                    if (!primaryKey.RecordDataExists)
                    {
                        if (ReadOnly && !SkipMissing) throw new ApplicationException("!primaryKey.RecordDataExists && ReadOnly && !SkipMissing)");
                        if (SkipMissing)
                        {
                            SkipMissingRecord(primaryKeyIndex);
                        }
                        else
                        {
                            _primaryKeysResolvedFromPublicKeyMissingRecordDataByReference ??= new HashSet<object>();
                            if (!_primaryKeysResolvedFromPublicKeyMissingRecordDataByReference.Add(resolvedPrimaryKey))
                                throw new ApplicationException("!_primaryKeysResolvedFromPublicKeyMissingRecordDataByReference.Add(resolvedPrimaryKey)");
                        }
                    }
                }

                protected override bool CheckResolvedFromPublicKeyMissingRecordData(int recordIndex, PrimaryKey primaryKey)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    if (!primaryKey.CompareBy.Reference.Equals(PrimaryKeys[recordIndex])) throw new ApplicationException("!identity.CompareBy.Reference.Equals(PrimaryKeys[recordIndex])");
                    if (_primaryKeysResolvedFromPublicKeyMissingRecordDataByReference == null) return false;
                    if (!_primaryKeysResolvedFromPublicKeyMissingRecordDataByReference.Contains(primaryKey)) return false;
                    if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("possiblyMissing.CheckExpectsAssignment()");
                    if (ReadOnly) throw new ApplicationException("ReadOnly");
                    if (WithoutRecordsData) throw new ApplicationException("WithoutRecordsData");
                    if (SkipMissing) throw new ApplicationException("SkipMissing");
                    return true;
                }
            }
        }
    }
}