using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using YourCompany.Configuration.EFCore.CollationAwareSorting.ChangeTracking;
using YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore.CollationAwareSorting;
using YourCompany.OLTP.StateOwnership;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        public abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            public abstract partial class WithoutIds
            {
                public new class After : WithoutIds,
                    RecordsDataAccess.IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData,
                    RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.AfterAlternateSorting>,
                    RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>,
                    RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>,
                    RecordsDataAccess.IReadIdentity<PrimaryKey.AfterAlternateSorting>,
                    RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>
                {
                    private readonly CollationAwareSortingUniqueKeyAdapter _afterId;
                    private readonly PrimaryKey.AfterAlternateSorting _afterAlternateSorting;

                    private readonly EntityEntrySortingKeyCreatingVisitor.Generic<TQueryableRecordData>
                        _sortingKeyCreatingEntryVisitor;

                    private PrimaryKey.WithoutExtraValues[] _primaryKeysWithoutRecordsData;
                    private PrimaryKey.AfterAlternateSorting[] _primaryKeysWithRecordsData;

                    public override IReadOnlyList<PrimaryKey> PrimaryKeys => WithoutRecordsData
                        ? _primaryKeysWithoutRecordsData
                        : _primaryKeysWithRecordsData;

                    protected internal After(YourCompanyDbContext<TConfiguration> context, Identity afterId) : base(context)
                    {
                        if (afterId is not UniqueKey uniqueKey) throw new ApplicationException("afterId is not UniqueKey uniqueKey");
                        _afterId = uniqueKey.AsAssignedSortingImplementedWith<CollationAwareSortingUniqueKeyAdapter>()
                            ?? throw new ApplicationException("uniqueKey.AsAssignedSortingImplementedWith<CollationAwareSortingUniqueKeyAdapter>() == null");
                        _afterAlternateSorting = uniqueKey.AsAssignedAfterSorting();
                        _sortingKeyCreatingEntryVisitor = new EntityEntrySortingKeyCreatingVisitor.Generic<TQueryableRecordData>();
                    }

                    RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                        RecordsDataAccess.IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData
                            .ForReadOnlyWithoutRecordsData() => ForReadOnlyWithoutIdsWithoutRecordsData();

                    public override RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                        ForReadOnlyWithoutIdsWithoutRecordsData()
                            => (this, ReadOnly = true, WithoutRecordsData = true).Item1;

                    RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>
                        RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.AfterAlternateSorting>
                            .ForReadOnlyWithRecordsData() => ForReadOnlyWithoutIdsWithRecordsDataAfterAlternateSorting();

                    public override RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>
                        ForReadOnlyWithoutIdsWithRecordsDataAfterAlternateSorting()
                            => (this, ReadOnly = true, WithoutRecordsData = false).Item1;

                    RecordsDataAccess.IReadIdentity<PrimaryKey.AfterAlternateSorting>
                        RecordsDataAccess.IReadOnly<PrimaryKey.AfterAlternateSorting>.Next => this;

                    RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>
                        RecordsDataAccess.IReadOnly<PrimaryKey.WithoutExtraValues>.Next => this;

                    RecordsDataAccess.IFinish
                        RecordsDataAccess.IReadIdentity<PrimaryKey.AfterAlternateSorting>.Next => this;

                    RecordsDataAccess.IFinish
                        RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>.Next => this;

                    protected override IQueryable<TQueryableRecordData> Query()
                    {
                        if (_queryable != null) throw new ApplicationException("_queryable != null");
                        EnsureBeforeResolvingWithoutIds();

                        var sortingKey = _afterId.SortingKey ?? throw new ApplicationException("sortingKey == null");

                        if (_afterId.PrefixedPrivatePrimaryKeySortingRequired)
                        {
                            sortingKey = sortingKey
                                .WithProperty(entityType: typeof(TQueryableRecordData),
                                    name: MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName,
                                    value: _afterAlternateSorting?.PrivateKey
                                        ?? (_afterId.PrefixedPrivatePrimaryKeySortingDescending ? long.MaxValue : 0),
                                    descending: _afterId.PrefixedPrivatePrimaryKeySortingDescending)
                                .ComparedBy<long>()
                                .ForSingleEntityQueries();
                        }

                        return _context.SubsetAfter<TQueryableRecordData>(sortingKey);
                    }

                    protected override void ResolvePrimaryKeys(
                        IReadOnlyList<RecordDataQueries.PrimaryKeyWithExists> readPrimaryKeys,
                        long[] existingRecordPrivateKeys)
                    {
                        if (readPrimaryKeys == null) throw new ArgumentNullException(nameof(readPrimaryKeys));
                        EnsureReadingForReadOnly();
                        if (_queryable == null) throw new ApplicationException("_queryable == null");
                        EnsureBeforeResolvingWithoutIds();

                        if (WithoutRecordsData)
                        {
                            _primaryKeysWithoutRecordsData = new PrimaryKey.WithoutExtraValues[readPrimaryKeys.Count];
                            ResolvePrimaryKeys(readPrimaryKeys, _primaryKeysWithoutRecordsData, existingRecordPrivateKeys);
                        }
                        else
                        {
                            _primaryKeysWithRecordsData = new PrimaryKey.AfterAlternateSorting[readPrimaryKeys.Count];
                            ResolvePrimaryKeys(readPrimaryKeys, _primaryKeysWithRecordsData, existingRecordPrivateKeys);
                        }
                    }

                    protected override void EnsurePrimaryKeyIsAssignedWithExistingRecordsData(
                        long privateKey,
                        PrimaryKey primaryKey,
                        RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData> record)
                    {
                        base.EnsurePrimaryKeyIsAssignedWithExistingRecordsData(privateKey, primaryKey, record);
                        EnsureAfterReadWithoutIds();

                        if (primaryKey is not PrimaryKey.AfterAlternateSorting afterAlternateSorting)
                            throw new ApplicationException("primaryKey is not PrimaryKey.AfterAlternateSorting afterAlternateSorting");

                        var entry = _context.Entry(record.RecordData);
                        if (entry.State == EntityState.Unchanged)
                        {
                            if (_context.Database.CurrentTransaction == null) throw new ApplicationException("!ReadOnly && _context.Database.CurrentTransaction == null");
                        }
                        else
                        {
                            if (!ReadOnly) throw new ApplicationException("entry.State != EntityState.Unchanged && !ReadOnly");
                            if (entry.State != EntityState.Detached)
                                throw new ApplicationException("ReadOnly && entry.State != EntityState.Detached && entry.State != EntityState.Unchanged");
                        }

                        var recordSortingKey = _sortingKeyCreatingEntryVisitor.CreateForSingleEntityQuery(
                            _afterId.SortingKey, entry);
                        if (afterAlternateSorting.CheckAlternateSortingIsAssigned()) throw new ApplicationException("_afterId != null && afterAlternateSorting.CheckAlternateSortingIsAssigned()");
                        if (_afterId.CanBeResolvedIntoPrivatePrimaryKey)
                        {
                            afterAlternateSorting.SetAlternateSorting(
                                new CollationAwareSortingUniqueKeyAdapter.NaturalPublicCursor(recordSortingKey));
                        }
                        else
                        {
                            if (!_afterId.PrefixedPrivatePrimaryKeySortingRequired) throw new ApplicationException("!_afterId.PrefixedPrivatePrimaryKeySortingRequired");
                            afterAlternateSorting.SetAlternateSorting(
                                new CollationAwareSortingUniqueKeyAdapter.PrivatePrimaryKeyPrefix(recordSortingKey)
                                {
                                    PrivatePrimaryKeySortingDescending = _afterId.PrefixedPrivatePrimaryKeySortingDescending
                                });
                        }
                    }

                    PrimaryKey.WithoutExtraValues
                        RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>
                            .GetReadRecordIdentity(int recordIndex, Identity originalIdentityWhenByIds)
                    {
                        EnsureNoContextLock();
                        EnsureAfterReadWithoutIds();
                        if (!WithoutRecordsData) throw new ApplicationException("!WithoutRecordsData");
                        if (_primaryKeysWithoutRecordsData == null) throw new ApplicationException("_primaryKeysWithoutRecordsData == null");
                        if (_primaryKeysWithRecordsData != null) throw new ApplicationException("_primaryKeysWithRecordsData != null");
                        return _primaryKeysWithoutRecordsData[recordIndex] ?? throw new ApplicationException("_primaryKeysWithoutRecordsData[recordIndex] == null");
                    }

                    PrimaryKey.AfterAlternateSorting
                        RecordsDataAccess.IReadIdentity<PrimaryKey.AfterAlternateSorting>
                            .GetReadRecordIdentity(int recordIndex, Identity originalIdentityWhenByIds)
                    {
                        EnsureNoContextLock();
                        EnsureAfterReadWithoutIds();
                        if (WithoutRecordsData) throw new ApplicationException("WithoutRecordsData");
                        if (_primaryKeysWithoutRecordsData != null) throw new ApplicationException("_primaryKeysWithoutRecordsData != null");
                        if (_primaryKeysWithRecordsData == null) throw new ApplicationException("_primaryKeysWithRecordsData == null");
                        return _primaryKeysWithRecordsData[recordIndex] ?? throw new ApplicationException("_primaryKeysWithRecordsData[recordIndex] == null");
                    }
                }
            }
        }
    }
}