using System;
using System.Collections.Generic;
using System.Linq;
using YourCompany.OLTP.StateOwnership;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        public abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            public abstract partial class WithoutIds
            {
                public new class NoSorting : WithoutIds,
                    RecordsDataAccess.IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData,
                    RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.WithoutExtraValues>,
                    RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>,
                    RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>
                {
                    private PrimaryKey.WithoutExtraValues[] _primaryKeys;

                    public override IReadOnlyList<PrimaryKey> PrimaryKeys => _primaryKeys;

                    protected internal NoSorting(YourCompanyDbContext<TConfiguration> context) : base(context) { }

                    RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                        RecordsDataAccess.IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData
                            .ForReadOnlyWithoutRecordsData() => ForReadOnlyWithoutIdsWithoutRecordsData();

                    public override RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                        ForReadOnlyWithoutIdsWithoutRecordsData()
                            => (this, ReadOnly = true, WithoutRecordsData = true).Item1;

                    RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                        RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.WithoutExtraValues>
                            .ForReadOnlyWithRecordsData() => ForReadOnlyWithoutIdsWithRecordsDataWithoutExtraValues();

                    public override RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
                        ForReadOnlyWithoutIdsWithRecordsDataWithoutExtraValues()
                            => (this, ReadOnly = true, WithoutRecordsData = false).Item1;

                    RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>
                        RecordsDataAccess.IReadOnly<PrimaryKey.WithoutExtraValues>.Next => this;

                    RecordsDataAccess.IFinish
                        RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>.Next => this;

                    protected override IQueryable<TQueryableRecordData> Query() => _context.Set<TQueryableRecordData>();

                    protected override void ResolvePrimaryKeys(
                        IReadOnlyList<RecordDataQueries.PrimaryKeyWithExists> readPrimaryKeys,
                        long[] existingRecordPrivateKeys)
                    {
                        if (readPrimaryKeys == null) throw new ArgumentNullException(nameof(readPrimaryKeys));
                        EnsureReadingForReadOnlyOrByModifyingWrapperOnly();
                        if (_queryable == null) throw new ApplicationException("_queryable == null");
                        EnsureBeforeResolvingWithoutIds();
                        _primaryKeys = new PrimaryKey.WithoutExtraValues[readPrimaryKeys.Count];
                        ResolvePrimaryKeys(readPrimaryKeys, _primaryKeys, existingRecordPrivateKeys);
                    }

                    protected override void EnsurePrimaryKeyIsAssignedWithExistingRecordsData(
                        long privateKey,
                        PrimaryKey primaryKey,
                        RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData> record)
                    {
                        base.EnsurePrimaryKeyIsAssignedWithExistingRecordsData(privateKey, primaryKey, record);
                        EnsureAfterReadWithoutIds();
                        if (primaryKey is not PrimaryKey.WithoutExtraValues)
                            throw new ApplicationException("primaryKey is not PrimaryKey.WithoutExtraValues");
                    }

                    PrimaryKey.WithoutExtraValues
                        RecordsDataAccess.IReadIdentity<PrimaryKey.WithoutExtraValues>
                            .GetReadRecordIdentity(int recordIndex, Identity originalIdentityWhenByIds)
                    {
                        EnsureNoContextLock();
                        EnsureAfterReadWithoutIds();
                        return _primaryKeys[recordIndex] ?? throw new ApplicationException("_primaryKeys[recordIndex] == null");
                    }
                }
            }
        }
    }
}