using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        : RecordsDataAccess.IReadOnly,
        RecordsDataAccess.IFinish
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        private readonly YourCompanyDbContext<TConfiguration> _context;
        private TaskCompletionSource _contextLock;

        public bool ContextIsLocked => _contextLock != null;
        public bool ReadOnly { get; private set; }
        public bool WithoutRecordsData { get; private set; }

        public abstract IReadOnlyList<PrimaryKey> PrimaryKeys { get; }

        protected YourCompanyDbContextLockingRecordDataReader(YourCompanyDbContext<TConfiguration> context)
            => _context = context ?? throw new ArgumentNullException(nameof(context));

        public static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
            ByIdsWithoutForcedReadIfModifying(
                Type recordDataType,
                Type queryableRecordDataType,
                YourCompanyDbContext<TConfiguration> context,
                IReadOnlyList<PrimaryKey> ids)
                => FactoriesCache.ByIdsWithoutForcedReadIfModifying(recordDataType, queryableRecordDataType, context, ids);

        public static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
            ByIds(
                Type recordDataType,
                Type queryableRecordDataType,
                YourCompanyDbContext<TConfiguration> context,
                IReadOnlyList<Identity> ids,
                bool skipMissingOrPreventCreation)
        {
            var byIds = FactoriesCache.ByIds(recordDataType, queryableRecordDataType, context, ids);
            if (byIds is not IByIdsSetSkipMissing setSkipMissing) throw new ApplicationException("byIds is not IByIdsSetSkipMissing setSkipMissing");
            setSkipMissing.SkipMissing = skipMissingOrPreventCreation;
            return byIds;
        }

        public static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
            After(
                Type recordDataType,
                Type queryableRecordDataType,
                YourCompanyDbContext<TConfiguration>
                context,
                Identity afterId)
                => FactoriesCache.After(recordDataType, queryableRecordDataType, context, afterId);

        public static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
            NoSorting(Type recordDataType, Type queryableRecordDataType, YourCompanyDbContext<TConfiguration> context)
                => FactoriesCache.NoSorting(recordDataType, queryableRecordDataType, context);

        public virtual RecordsDataAccess.IReadOnly<PrimaryKey> ForReadOnlyByIdsWithoutRecordsData() => null;
        public virtual RecordsDataAccess.IReadOnly<PrimaryKey> ForReadOnlyByIdsWithRecordsData() => null;

        public virtual RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
            ForReadOnlyWithoutIdsWithoutRecordsData() => null;

        public virtual RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>
            ForReadOnlyWithoutIdsWithRecordsDataAfterAlternateSorting() => null;

        public virtual RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
            ForReadOnlyWithoutIdsWithRecordsDataWithoutExtraValues() => null;

        public bool FilterAfterSortingWithoutIds(object specification)
        {
            if (specification == null) throw new ArgumentNullException(nameof(specification));
            EnsureNoContextLock();
            if (PrimaryKeys != null) throw new ApplicationException("PrimaryKeys != null");
            return FilterAfterSortingWithoutIdsBeforeRead(specification);
        }

        public async Task<int> ReadWithoutModifying(int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
        {
            EnsureNoContextLock();
            if (!ReadOnly) throw new ApplicationException("!ReadOnly");

            Exception readException = null;
            await LockContext();
            try
            {
                return await Read(batchSize, recordsCountToSkip, cancellationToken);
            }
            catch (Exception ex)
            {
                readException = ex;
                throw;
            }
            finally
            {
                ReleaseContextLock(readException);
            }
        }

        protected virtual async Task<int> Read(int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
        {
            EnsureReadingForReadOnly();

            var existingRecordPrivateKeys = await ResolvePrimaryKeys(batchSize, recordsCountToSkip, cancellationToken);
            if (existingRecordPrivateKeys?.Count > batchSize) throw new ApplicationException("existingRecordPrivateKeys?.Count > batchSize");
            int recordsCount = PrimaryKeys?.Count ?? throw new ApplicationException("PrimaryKeys == null");
            if (recordsCount == 0 && existingRecordPrivateKeys != null) throw new ApplicationException("recordsCount == 0 && existingRecordPrivateKeys != null");

            if (!WithoutRecordsData && existingRecordPrivateKeys != null)
            {
                await ReadRecordDataByPrivateKeys(existingRecordPrivateKeys, cancellationToken);
                EnsurePrimaryKeysAreAssignedWithExistingRecordsData();
            }

            return recordsCount;
        }

        protected virtual void EnsurePrimaryKeysAreAssignedWithExistingRecordsData()
        {
            EnsureReadingForReadOnly();
            if (WithoutRecordsData) throw new ApplicationException("WithoutRecordsData");
            if (PrimaryKeys == null) throw new ApplicationException("PrimaryKeys == null");

            for (int recordIndex = 0; recordIndex < PrimaryKeys.Count; recordIndex++)
            {
                var primaryKey = PrimaryKeys[recordIndex];
                if (CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData(recordIndex, primaryKey)) continue;
                if (primaryKey == null) throw new ApplicationException("primaryKey == null && !CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData(i, primaryKey)");
                long privateKey = primaryKey.PrivateKey ?? throw new ApplicationException("!primaryKey.PrivateKey.HasValue");
                EnsurePrimaryKeyIsAssignedWithExistingRecordsData(privateKey, primaryKey);
                if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("primaryKey.CheckExpectsAssignment()");
            }
        }

        protected virtual bool CheckResolvedFromPublicKeyMissingRecordData(int recordIndex, PrimaryKey primaryKey) => false;

        public virtual Task Finish(CancellationToken cancellationToken) => Task.CompletedTask;

        public virtual object GetRecordDataAfterAccess(int recordIndex, PrimaryKey primaryKey)
        {
            EnsureNoContextLock();
            if (WithoutRecordsData) throw new ApplicationException("WithoutRecordsData");

            EnsureMatchingResolvedPrimaryKey(recordIndex, primaryKey);
            if (CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData(recordIndex, primaryKey))
                return null;

            if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("primaryKey.CheckExpectsAssignment()");
            long privateKey = primaryKey.PrivateKey ?? throw new ApplicationException("!primaryKey.PrivateKey.HasValue");
            return GetExistingRecordDataIfReadByPrivateKey(privateKey);
        }

        protected virtual bool FilterAfterSortingWithoutIdsBeforeRead(object specification) => false;

        protected abstract Task<IReadOnlyList<long>> ResolvePrimaryKeys(
            int batchSize, int recordsCountToSkip, CancellationToken cancellationToken);

        protected abstract bool CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData(
            int recordIndex, PrimaryKey possiblyMissing);

        protected abstract void EnsurePrimaryKeyIsAssignedWithExistingRecordsData(long privateKey, PrimaryKey primaryKey);

        protected abstract Task ReadRecordDataByPrivateKeys(
            IReadOnlyList<long> existingRecordPrivateKeys, CancellationToken cancellationToken);

        protected abstract object GetExistingRecordDataIfReadByPrivateKey(long primaryKey);

        public Task LockContext()
        {
            EnsureNoContextLock();
            _contextLock = new TaskCompletionSource();
            return _context.Lock(_contextLock.Task);
        }

        public void ReleaseContextLock(Exception trySetException = null)
        {
            var contextLock = _contextLock;
            _contextLock = null;
            if (trySetException != null)
            {
                contextLock?.TrySetException(trySetException);
            }
            else
            {
                if (contextLock == null) throw new ApplicationException("trySetException == null && contextLock == null");
                contextLock.SetResult();
            }
        }

        protected void EnsureContextLocked()
        {
            if (_contextLock == null) throw new ApplicationException("_contextLock == null");
        }

        protected void EnsureNoContextLock()
        {
            if (_contextLock != null) throw new ApplicationException("_contextLock != null");
        }

        protected void EnsureReadingForReadOnly()
        {
            EnsureContextLocked();
            if (!ReadOnly) throw new ApplicationException("!_preventFurtherLockingByOriginalReader && !ReadOnly");
        }

        protected void EnsureMatchingResolvedPrimaryKey(int recordIndex, PrimaryKey primaryKey)
        {
            if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
            if (PrimaryKeys == null) throw new ApplicationException("PrimaryKeys == null");
            if (!primaryKey.CompareBy.Reference.Equals(PrimaryKeys[recordIndex])) throw new ApplicationException("!primaryKey.CompareBy.Reference.Equals(PrimaryKeys[recordIndex])");
        }
    }
}