using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public class YourCompanyDbContextRecordsDataAccessAdapter<TConfiguration> : RecordsDataAccess.IStarting,
        RecordsDataAccess.IAfterSortingByIds,
        RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting>,
        RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues>,
        RecordsDataAccess.IReadBeforeModifying,
        RecordsDataAccess.IFinish
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        private bool _disposed;
        private YourCompanyDbContextLockingRecordDataReader<TConfiguration> _reader;
        private IDbContextTransaction _contextCreatorTransaction;

        protected Type RecordDataType { get; }
        protected YourCompanyDbContext<TConfiguration> Context { get; }
        protected bool ContextCreator { get; }

        public YourCompanyDbContextRecordsDataAccessAdapter(
            Type recordDataType, YourCompanyDbContext<TConfiguration> context, bool contextCreator)
        {
            RecordDataType = recordDataType ?? throw new ArgumentNullException(nameof(recordDataType));
            Context = context ?? throw new ArgumentNullException(nameof(context));
            ContextCreator = contextCreator;
        }

        public int MaxRecordsInBatch
            => Context.Configuration.ByRecordDataTypeFullName?.TryGetValue(RecordDataType.FullName, out var by) == true
                ? by.MaxRecordsInBatch ?? Context.Configuration.DefaultMaxRecordsInBatch
                : Context.Configuration.DefaultMaxRecordsInBatch;

        public virtual RecordsDataAccess.IAfterSortingByIdsWithoutReading ByIdsWithoutForcedReadIfModifying(
            IReadOnlyList<PrimaryKey> ids)
        {
            EnsureNotDisposed();
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.ByIdsWithoutForcedReadIfModifying(
                RecordDataType, queryableRecordDataType, Context, ids);
            return null;
        }

        public virtual RecordsDataAccess.IAfterSortingByIds ByIds(
            IReadOnlyList<Identity> ids, bool skipMissingOrPreventCreation)
        {
            EnsureNotDisposed();
            if (_reader != null)
            {
                if (!ReferenceEquals(_reader.PrimaryKeys, ids))
                    throw new ApplicationException("!ReferenceEquals(_reader.PrimaryKeys, ids)");
                return this;
            }
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.ByIds(
                RecordDataType, queryableRecordDataType, Context, ids, skipMissingOrPreventCreation);
            return this;
        }

        public virtual RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting> After(Identity afterId)
        {
            EnsureNotDisposed();
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.After(
                RecordDataType, queryableRecordDataType, Context, afterId);
            return this;
        }

        public virtual RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues> NoSorting()
        {
            EnsureNotDisposed();
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.NoSorting(
                RecordDataType, queryableRecordDataType, Context);
            return this;
        }

        public bool FilterAfterSorting(object specification)
        {
            EnsureNotDisposed();
            if (specification == null) throw new ArgumentNullException(nameof(specification));
            if (_reader == null) throw new ApplicationException("_reader == null");
            return _reader.FilterAfterSortingWithoutIds(specification);
        }

        RecordsDataAccess.IReadOnly<PrimaryKey>
            RecordsDataAccess.IAfterSortingByIdsForReadOnly
                .ForReadOnlyByIdsWithoutRecordsData() => _reader?.ForReadOnlyByIdsWithoutRecordsData();

        RecordsDataAccess.IReadOnly<PrimaryKey>
            RecordsDataAccess.IAfterSortingByIdsForReadOnly
                .ForReadOnlyByIdsWithRecordsData() => _reader?.ForReadOnlyByIdsWithRecordsData();

        RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
            RecordsDataAccess.IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData
                .ForReadOnlyWithoutRecordsData() => _reader?.ForReadOnlyWithoutIdsWithoutRecordsData();

        RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>
            RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.AfterAlternateSorting>
                .ForReadOnlyWithRecordsData() => _reader?.ForReadOnlyWithoutIdsWithRecordsDataAfterAlternateSorting();

        RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
            RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.WithoutExtraValues>
                .ForReadOnlyWithRecordsData() => _reader?.ForReadOnlyWithoutIdsWithRecordsDataWithoutExtraValues();

        RecordsDataAccess.IReadBeforeModifying<PrimaryKey>
            RecordsDataAccess.IAfterSortingByIdsForModifying.ForModifyingAfterReadingByIds()
        {
            if (_reader == null) throw new ApplicationException("_reader == null");
            _reader.ForModifyingAfterReadingByIds();
            var (reader, readBeforeModifying) = _reader.BeforeModifying<PrimaryKey>(this, this);
            _reader = reader;
            return readBeforeModifying;
        }

        RecordsDataAccess.IReadBeforeModifying<PrimaryKey.AfterAlternateSorting>
            RecordsDataAccess.IAfterSortingWithoutIdsForModifying<PrimaryKey.AfterAlternateSorting>
                .ForModifyingAfterReading()
        {
            if (_reader == null) throw new ApplicationException("_reader == null");
            var (reader, readBeforeModifying) = _reader.BeforeModifying<PrimaryKey.AfterAlternateSorting>(this, this);
            _reader = reader;
            return readBeforeModifying;
        }

        RecordsDataAccess.IReadBeforeModifying<PrimaryKey.WithoutExtraValues>
            RecordsDataAccess.IAfterSortingWithoutIdsForModifying<PrimaryKey.WithoutExtraValues>
                .ForModifyingAfterReading()
        {
            if (_reader == null) throw new ApplicationException("_reader == null");
            var (reader, readBeforeModifying) = _reader.BeforeModifying<PrimaryKey.WithoutExtraValues>(this, this);
            _reader = reader;
            return readBeforeModifying;
        }

        public async Task<int> ReadAndLockForChangesPersisting(
            int batchSize, int recordsCountToSkip, CancellationToken cancellationToken)
        {
            EnsureNotDisposed();
            if (_reader == null) throw new ApplicationException("_reader == null");
            if (_contextCreatorTransaction != null) throw new ApplicationException("_contextCreatorTransaction != null");
            await _reader.LockContext();
            if (ContextCreator) await BeginTransactionByContextCreator(cancellationToken);
            await _reader.ReadAndLockForChangesPersisting(batchSize, recordsCountToSkip, cancellationToken);
            _reader.ReleaseContextLock();
            return _reader.PrimaryKeys?.Count ?? throw new ApplicationException("_reader.PrimaryKeys == null");
        }

        public async Task Finish(CancellationToken cancellationToken)
        {
            EnsureNotDisposed();
            if (_reader == null) throw new ApplicationException("_reader == null");
            await _reader.LockContext();
            await _reader.Finish(cancellationToken);
            if (ContextCreator) await CommitTransactionByContextCreator(cancellationToken);
            _reader.ReleaseContextLock();
        }

        public object GetRecordDataAfterAccess(int recordIndex, PrimaryKey primaryKey)
        {
            EnsureNotDisposed();
            if (_reader == null) throw new ApplicationException("_reader == null");
            return _reader.GetRecordDataAfterAccess(recordIndex, primaryKey);
        }

        public async virtual Task Dispose(CancellationToken cancellationToken, Exception runException = null)
        {
            bool wasDisposed = _disposed;
            _disposed = true;

            var reader = _reader;
            _reader = null;

            var contextCreatorTransaction = _contextCreatorTransaction;
            _contextCreatorTransaction = null;

            if (wasDisposed && reader != null)
                throw new ApplicationException("wasDisposed && reader != null", runException);
            if (wasDisposed && contextCreatorTransaction != null)
                throw new ApplicationException("wasDisposed && contextCreatorTransaction != null", runException);
            if (contextCreatorTransaction != null && reader == null)
                throw new ApplicationException("contextCreatorTransaction != null && reader == null", runException);
            if (contextCreatorTransaction != null && !ContextCreator)
                throw new ApplicationException("!ContextCreator && contextCreatorTransaction != null", runException);

            if (wasDisposed) return;

            if (reader != null && reader.ContextIsLocked) reader.ReleaseContextLock();

            if (!ContextCreator) return;

            var disposeLock = new TaskCompletionSource();
            await Context.Lock(disposeLock.Task);

            Exception rollbackException = null;

            try
            {
                try
                {
                    try
                    {
                        if (contextCreatorTransaction != null)
                            await contextCreatorTransaction.RollbackAsync(CancellationToken.None);
                    }
                    catch (Exception ex)
                    {
                        rollbackException = ex;
                        throw;
                    }
                }
                finally
                {
                    try
                    {
                        await Context.DisposeAsync();
                    }
                    catch (Exception) when (rollbackException == null)
                    {
                        throw;
                    }
                    catch (Exception ex) when (rollbackException != null)
                    {
                        throw new AggregateException(rollbackException, ex);
                    }
                }
            }
            catch (Exception ex) when (runException == null)
            {
                disposeLock.SetException(ex);
                throw;
            }
            catch (Exception ex) when (runException != null)
            {
                var disposeException = new AggregateException(runException, ex);
                disposeLock.SetException(disposeException);
                throw disposeException;
            }

            disposeLock.SetResult();
        }

        protected void EnsureNotDisposed()
        {
            if (_disposed) throw new ObjectDisposedException(nameof(YourCompanyDbContextRecordsDataAccessAdapter<TConfiguration>));
        }

        protected void EnsureTransactionAfterRead()
        {
            if (ContextCreator && _contextCreatorTransaction == null) throw new ApplicationException("ContextCreator && _contextCreatorTransaction == null");
            if (Context.Database.CurrentTransaction == null) throw new ApplicationException("Context.Database.CurrentTransaction == null");
            if (_contextCreatorTransaction != null && _contextCreatorTransaction != Context.Database.CurrentTransaction)
                throw new ApplicationException("_contextCreatorTransaction != null && _contextCreatorTransaction != Context.Database.CurrentTransaction");
        }

        private async Task BeginTransactionByContextCreator(CancellationToken cancellationToken)
        {
            EnsureNotDisposed();
            if (!ContextCreator) throw new ApplicationException("!ContextCreator");
            if (!_reader.ContextIsLocked) throw new ApplicationException("!_reader.ContextIsLocked");
            if (_contextCreatorTransaction != null) throw new ApplicationException("_contextCreatorTransaction != null");
            if (Context.Database.CurrentTransaction != null) throw new ApplicationException("Context.Database.CurrentTransaction != null");
            _contextCreatorTransaction = await Context.Database.BeginTransactionAsync(IsolationLevel.ReadCommitted, cancellationToken);
        }

        private async Task CommitTransactionByContextCreator(CancellationToken cancellationToken)
        {
            EnsureNotDisposed();
            EnsureTransactionAfterRead();
            if (!ContextCreator) throw new ApplicationException("!ContextCreator");
            if (!_reader.ContextIsLocked) throw new ApplicationException("!_reader.ContextIsLocked");

            var contextCreatorTransaction = _contextCreatorTransaction;
            _contextCreatorTransaction = null;
            if (contextCreatorTransaction == null) throw new ApplicationException("contextCreatorTransaction == null");

            await contextCreatorTransaction.CommitAsync(cancellationToken);
            await Context.DisposeAsync();
        }
    }
}