using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using YourCompany.Configuration.EFCore.CollationAwareSorting.ChangeTracking;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        public abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
            : YourCompanyDbContextLockingRecordDataReader<TConfiguration>
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            private IReadOnlyDictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>
                _primaryKeysWithRecordDataByPrivateKey;

            private EntityEntryPropertiesSettingVisitor.Generic<TQueryableRecordData> _sortingKeyValuesSettingVisitor;

            public EntityEntryPropertiesSettingVisitor.Generic<TQueryableRecordData> SortingKeyValuesSettingVisitor
                => _sortingKeyValuesSettingVisitor ??= new();

            private SingleEntityQuery(YourCompanyDbContext<TConfiguration> context) : base(context) { }

            protected override YourCompanyDbContextLockingRecordDataReader<TConfiguration>
                WrapForModifying<TPrimaryKey>(
                    RecordsDataAccess.IReadBeforeModifying readBeforeModifying, RecordsDataAccess.IFinish finishNext)
                    => new ReadBeforeModifying<TPrimaryKey>(this, readBeforeModifying, finishNext);

            protected override async Task ReadRecordDataByPrivateKeys(
                IReadOnlyList<long> existingRecordPrivateKeys, bool lockAndTrack, CancellationToken cancellationToken)
            {
                if (existingRecordPrivateKeys == null) throw new ArgumentNullException(nameof(existingRecordPrivateKeys));
                if (existingRecordPrivateKeys.Count < 1) throw new ApplicationException("existingRecordPrivateKeys.Count < 1");
                EnsureReadingForReadOnlyOrByModifyingWrapperOnly();
                if (WithoutRecordsData) throw new ApplicationException("WithoutRecordsData");
                if (PrimaryKeys == null) throw new ApplicationException("PrimaryKeys == null");
                if (_primaryKeysWithRecordDataByPrivateKey != null) throw new ApplicationException("_primaryKeysWithRecordDataByPrivateKey != null");
                if (lockAndTrack != !ReadOnly) throw new ApplicationException("lockAndTrack != !ReadOnly");
                if (lockAndTrack && _context.Database.CurrentTransaction == null) throw new ApplicationException("lockAndTrack && _context.Database.CurrentTransaction == null");

                var previouslyLockedRecords = _context
                    .GetPrimaryKeysWithLocalRecordDataToDictionary<TRecordData, TQueryableRecordData>(existingRecordPrivateKeys);

                if (previouslyLockedRecords?.Count > 0)
                {
                    if (_context.Database.CurrentTransaction == null) throw new ApplicationException("_context.Database.CurrentTransaction == null");
                    if (previouslyLockedRecords.Count > existingRecordPrivateKeys.Count) throw new ApplicationException("previouslyLockedRecords.Count > existingRecordPrivateKeys.Count");
                    if (previouslyLockedRecords.Count == existingRecordPrivateKeys.Count)
                        _primaryKeysWithRecordDataByPrivateKey = previouslyLockedRecords;
                }

                _primaryKeysWithRecordDataByPrivateKey ??= await _context.GetPrimaryKeysWithRecordDataToDictionary<TRecordData, TQueryableRecordData>(
                    existingRecordPrivateKeys, lockAndTrack, cancellationToken) ?? throw new ApplicationException("_primaryKeysWithRecordDataByPrivateKey == null");

                for (int i = 0; i < existingRecordPrivateKeys.Count; i++)
                    if (!_primaryKeysWithRecordDataByPrivateKey.ContainsKey(existingRecordPrivateKeys[i]))
                        throw new ApplicationException("!_primaryKeysWithRecordDataByPrivateKey.ContainsKey(existingRecordPrivateKeys[i])");
            }

            protected sealed override void EnsurePrimaryKeyIsAssignedWithExistingRecordsData(
                long privateKey, PrimaryKey primaryKey)
            {
                if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                EnsureReadingForReadOnlyOrByModifyingWrapperOnly();
                EnsureAfterReadWithRecordsData();

                if (!_primaryKeysWithRecordDataByPrivateKey.TryGetValue(privateKey, out var record))
                    throw new ApplicationException("!_primaryKeysWithRecordDataByPrivateKey.TryGetValue(privateKey, out var record)");

                EnsurePrimaryKeyIsAssignedWithExistingRecordsData(privateKey, primaryKey, record);
            }

            protected virtual void EnsurePrimaryKeyIsAssignedWithExistingRecordsData(
                long privateKey,
                PrimaryKey primaryKey,
                RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData> record)
            {
                if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                EnsureReadingForReadOnlyOrByModifyingWrapperOnly();
                EnsureAfterReadWithRecordsData();

                if (primaryKey.CheckPublicKeyIsAssigned())
                {
                    if (primaryKey.PublicKey != record.PublicKey) throw new ApplicationException("primaryKey.PublicKey != record.PublicKey");
                }
                else
                {
                    primaryKey.SetPublicKey(record.PublicKey);
                }

                if (!ReadOnly)
                {
                    if (_context.Database.CurrentTransaction == null) throw new ApplicationException("!ReadOnly && _context.Database.CurrentTransaction == null");
                    var entry = _context.Entry(record.RecordData);
                    if (entry.State != EntityState.Unchanged) throw new ApplicationException("!ReadOnly && entry.State != EntityState.Unchanged");
                }
            }

            protected override object GetExistingRecordDataIfReadByPrivateKey(long primaryKey)
            {
                if (_primaryKeysWithRecordDataByPrivateKey == null) throw new ApplicationException("_primaryKeysWithRecordDataByPrivateKey == null");
                _primaryKeysWithRecordDataByPrivateKey.TryGetValue(primaryKey, out var record);
                return record.RecordData;
            }

            protected void EnsureAfterReadWithRecordsData()
            {
                if (WithoutRecordsData) throw new ApplicationException("WithoutRecordsData");
                if (PrimaryKeys == null) throw new ApplicationException("PrimaryKeys == null");
                if (_primaryKeysWithRecordDataByPrivateKey == null) throw new ApplicationException("_primaryKeysWithRecordDataByPrivateKey == null");
            }
        }
    }
}