using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore.CollationAwareSorting;
using YourCompany.OLTP.StateOwnership;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        internal interface IByIdsSetSkipMissing
        {
            bool SkipMissing { set; }
        }

        public abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
        {
            public new abstract partial class ByIds : SingleEntityQuery<TRecordData, TQueryableRecordData>,
                RecordsDataAccess.IReadOnly<PrimaryKey>,
                RecordsDataAccess.IReadIdentity<PrimaryKey>
            {
                protected abstract bool SkipMissing { get; }

                RecordsDataAccess.IReadIdentity<PrimaryKey> RecordsDataAccess.IReadOnly<PrimaryKey>.Next => this;
                RecordsDataAccess.IFinish RecordsDataAccess.IReadIdentity<PrimaryKey>.Next => this;

                private ByIds(YourCompanyDbContext<TConfiguration> context) : base(context) { }

                public override RecordsDataAccess.IReadOnly<PrimaryKey>
                    ForReadOnlyByIdsWithoutRecordsData() => (this, ReadOnly = true, WithoutRecordsData = true).Item1;

                public override RecordsDataAccess.IReadOnly<PrimaryKey>
                    ForReadOnlyByIdsWithRecordsData() => (this, ReadOnly = true, WithoutRecordsData = false).Item1;

                public override RecordsDataAccess.IReadBeforeModifying<PrimaryKey>
                    ForModifyingAfterReadingByIds()
                        => ((RecordsDataAccess.IReadBeforeModifying<PrimaryKey>)null,
                            ReadOnly = false,
                            WithoutRecordsData = false).Item1;

                protected abstract void SkipMissingRecord(int recordIndex);

                protected override bool CheckToSkipPrimaryKeyAfterResolvingWithExistingRecordsData(
                    int recordIndex, PrimaryKey possiblyMissing)
                {
                    if (possiblyMissing == null)
                    {
                        if (!SkipMissing) throw new ApplicationException("possiblyMissing == null && !SkipMissing");
                        return true;
                    }

                    if (!possiblyMissing.CheckPrivateKeyIsAssigned())
                    {
                        if (ReadOnly) throw new ApplicationException("!possiblyMissing.CheckPrivateKeyIsAssigned() && ReadOnly");
                        if (WithoutRecordsData) throw new ApplicationException("WithoutRecordsData");
                        if (SkipMissing) throw new ApplicationException("!possiblyMissing.CheckPrivateKeyIsAssigned() && SkipMissing");
                        return true;
                    }

                    return CheckResolvedFromPublicKeyMissingRecordData(recordIndex, possiblyMissing);
                }

                protected override void EnsurePrimaryKeyIsAssignedWithExistingRecordsData(
                    long privateKey,
                    PrimaryKey primaryKey,
                    RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData> record)
                {
                    base.EnsurePrimaryKeyIsAssignedWithExistingRecordsData(privateKey, primaryKey, record);
                    if (ReadOnly) return;

                    var ensureSortingKeyMatchingRecordData = primaryKey
                        .AsAssignedSortingImplementedWith<CollationAwareSortingUniqueKeyAdapter>();

                    if (ensureSortingKeyMatchingRecordData != null)
                    {
                        var expectedValues = ensureSortingKeyMatchingRecordData.SortingKey ?? throw new ApplicationException("ensureSortingKeyMatchingRecordData.SortingKey == null");
                        var entry = _context.Entry(record.RecordData);
                        if (entry.State != EntityState.Unchanged) throw new ApplicationException("entry.State != EntityState.Unchanged");
                        SortingKeyValuesSettingVisitor.SetSingleEntityQueryValuesTo(expectedValues, entry);
                        if (entry.State != EntityState.Unchanged) throw new ApplicationException("entry.State != EntityState.Unchanged");
                    }
                }

                PrimaryKey RecordsDataAccess.IReadIdentity<PrimaryKey>.GetReadRecordIdentity(
                    int recordIndex, Identity originalIdentityWhenByIds)
                {
                    EnsureNoContextLock();
                    var primaryKey = PrimaryKeys[recordIndex];
                    if (primaryKey == null && !SkipMissing) throw new ApplicationException("primaryKey == null && !SkipMissing");
                    return primaryKey;
                }

                protected static void ValidateIdsCompatibility(IReadOnlyList<Identity> ids)
                {
                    if (ids == null) throw new ArgumentNullException(nameof(ids));
                    for (int recordIndex = 0; recordIndex < ids.Count; recordIndex++)
                    {
                        var uniqueKey = ids[recordIndex] as UniqueKey ?? throw new ApplicationException("id is not UniqueKey");
                        _ = uniqueKey.AsAssignedSortingImplementedWith<CollationAwareSortingUniqueKeyAdapter>();
                        var originalIdentityReference = uniqueKey.AsPrimaryKey()?.AsWithoutExtraValues()?.OriginalIdentityReference;
                        if (originalIdentityReference != null && originalIdentityReference is not UniqueKey)
                            throw new ApplicationException("originalIdentityReference != null && originalIdentityReference is not UniqueKey");
                    }
                }

                public class WithoutForcedReadIfModifying : ByIds
                {
                    private readonly IReadOnlyList<PrimaryKey> _primaryKeys;

                    public override IReadOnlyList<PrimaryKey> PrimaryKeys => _primaryKeys;
                    protected override bool SkipMissing => false;

                    protected internal WithoutForcedReadIfModifying(
                        YourCompanyDbContext<TConfiguration> context, IReadOnlyList<PrimaryKey> ids)
                        : base(context)
                    {
                        if (ids == null) throw new ArgumentNullException(nameof(ids));
                        if (ids.Count < 1) throw new ApplicationException("ids.Count < 1");
                        ValidateIdsCompatibility(ids);
                        _primaryKeys = ids;
                    }

                    protected override void SkipMissingRecord(int recordIndex)
                        => throw new ApplicationException(nameof(WithoutForcedReadIfModifying));
                }

                public class WithForcedReadIfModifying : ByIds, IByIdsSetSkipMissing
                {
                    private readonly IReadOnlyList<PrimaryKey> _primaryKeys;
                    private readonly IList<PrimaryKey> _primaryKeysEditableReference;
                    private bool _skipMissing;

                    public override IReadOnlyList<PrimaryKey> PrimaryKeys => _primaryKeys;
                    bool IByIdsSetSkipMissing.SkipMissing { set => _skipMissing = value; }
                    protected override bool SkipMissing => _skipMissing;

                    protected internal WithForcedReadIfModifying(
                        YourCompanyDbContext<TConfiguration> context, IReadOnlyList<Identity> ids)
                        : base(context)
                    {
                        if (ids == null) throw new ArgumentNullException(nameof(ids));
                        if (ids.Count == 0) throw new ApplicationException("ids.Count == 0");
                        ValidateIdsCompatibility(ids);

                        var primaryKeys = new PrimaryKey[ids.Count];
                        for (int recordIndex = 0; recordIndex < ids.Count; recordIndex++)
                        {
                            var uniqueKey = ids[recordIndex] as UniqueKey ?? throw new ApplicationException("id is not UniqueKey");
                            primaryKeys[recordIndex] = uniqueKey.AsPrimaryKey() ?? new PrimaryKey.WithoutExtraValues(uniqueKey);
                        }

                        _primaryKeys = primaryKeys;
                        _primaryKeysEditableReference = primaryKeys;
                    }

                    protected override void SkipMissingRecord(int recordIndex)
                    {
                        if (!SkipMissing) throw new ApplicationException("!SkipMissing");
                        _primaryKeysEditableReference[recordIndex] = null;
                    }
                }
            }
        }
    }
}