using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore.CollationAwareSorting;
using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    internal abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        internal abstract partial class SingleEntityQuery<TRecordData, TQueryableRecordData>
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            internal partial class ReadBeforeModifying<TPrimaryKey>
            {
                public override async Task Finish(CancellationToken cancellationToken)
                {
                    EnsureContextLockedModifyingOnly();
                    EnsureApplyingChanges();
                    ApplyChanges();
                    await _context.SaveChangesAsync(cancellationToken);
                    ResolvePrivateKeysAfterSaveChanges();
                }

                protected void ApplyChanges()
                {
                    EnsureContextLockedModifyingOnly();
                    EnsureApplyingChanges();

                    bool ensureUnchangedBeforeModifying = _context.Configuration.EnableStateOwnershipConflictingChangesDetection;
                    if (ensureUnchangedBeforeModifying)
                        EnsureNoUnexpectedContextChangesBeforeApplyingNewChanges();

                    for (int i = 0; i < _reader.PrimaryKeys.Count; i++)
                    {
                        var primaryKey = _reader.PrimaryKeys[i];
                        var modifyingEntriesPair = _modifyingEntries[i];
                        if (primaryKey == null)
                        {
                            if (modifyingEntriesPair != default) throw new ApplicationException("modifyingEntriesPair != default");
                            continue;
                        }

                        var privateKeyProperty = EntityEntryModifyingVisitor.ApplyChanges(
                            i, modifyingEntriesPair, ensureUnchangedBeforeModifying);
                        EnsurePrimaryKeyMatchesAfterApplyingChanges(
                            i, primaryKey, modifyingEntriesPair.LockedOrCreatedRecordData, privateKeyProperty);

                        if (_reader.GetRecordDataAfterAccess(i, primaryKey) == null)
                            modifyingEntriesPair.LockedOrCreatedRecordData.State = EntityState.Added;
                    }

                    ChangesApplied = true;
                }

                protected void EnsurePrimaryKeyMatchesAfterApplyingChanges(
                    int recordDataIndex,
                    PrimaryKey primaryKey,
                    EntityEntry<TQueryableRecordData> changedRecordData,
                    PropertyEntry<TQueryableRecordData, long> privateKeyProperty)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    if (changedRecordData == null) throw new ArgumentNullException(nameof(changedRecordData));
                    if (privateKeyProperty == null) throw new ArgumentNullException(nameof(privateKeyProperty));
                    if (changedRecordData.State != EntityState.Unchanged) throw new ApplicationException("createdRecordData.State != EntityState.Unchanged");
                    EnsureContextLockedModifyingOnly();
                    EnsureApplyingChanges();

                    if (!primaryKey.CheckPrivateKeyIsAssigned()
                        || _reader.CheckResolvedFromPublicKeyMissingRecordData(recordDataIndex, primaryKey))
                    {
                        if (_reader.GetRecordDataAfterAccess(recordDataIndex, primaryKey) != null)
                            throw new ApplicationException("_reader.GetRecordDataAfterAccess(i, primaryKey) != null");
                        SetSortingKeyPropertiesToCreatedRecord(primaryKey, changedRecordData);
                        if (privateKeyProperty.CurrentValue > 0) throw new ApplicationException("privateKeyProperty.CurrentValue > 0");
                    }
                    else
                    {
                        if (_reader.GetRecordDataAfterAccess(recordDataIndex, primaryKey) == null)
                            throw new ApplicationException("_reader.GetRecordDataAfterAccess(i, primaryKey) == null");
                        if (privateKeyProperty.CurrentValue < 0) throw new ApplicationException("privateKeyProperty.CurrentValue < 0");
                    }

                    if (privateKeyProperty.CurrentValue != primaryKey.PrivateKey)
                        throw new ApplicationException("privateKeyProperty.CurrentValue != primaryKey.PrivateKey");
                }

                protected void SetSortingKeyPropertiesToCreatedRecord(
                    PrimaryKey primaryKey, EntityEntry<TQueryableRecordData> unchangedOrPropertiesChangingEntry)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    if (unchangedOrPropertiesChangingEntry == null) throw new ArgumentNullException(nameof(unchangedOrPropertiesChangingEntry));
                    EnsureContextLockedModifyingOnly();
                    EnsureApplyingChanges();

                    var withoutExtraValues = primaryKey.AsWithoutExtraValues() ?? throw new ApplicationException("primaryKey.AsWithoutExtraValues() == null");
                    var setPropertiesFromAlternateUniqueKey = withoutExtraValues
                        .AsAssignedSortingImplementedWith<CollationAwareSortingUniqueKeyAdapter>();

                    if (setPropertiesFromAlternateUniqueKey != null)
                        SortingKeyValuesSettingVisitor.SetSingleEntityQueryValuesTo(
                            setPropertiesFromAlternateUniqueKey.SortingKey, unchangedOrPropertiesChangingEntry);
                }

                protected void ResolvePrivateKeysAfterSaveChanges()
                {
                    EnsureContextLockedModifyingOnly();
                    EnsureAfterPopulatingEntries();
                    if (!ChangesApplied) throw new ApplicationException("!ChangesApplied");

                    for (int i = 0; i < _reader.PrimaryKeys.Count; i++)
                    {
                        var primaryKey = _reader.PrimaryKeys[i];
                        var modifyingEntriesPair = _modifyingEntries[i];
                        if (primaryKey == null)
                        {
                            if (modifyingEntriesPair != default) throw new ApplicationException("modifyingEntriesPair != default");
                            continue;
                        }

                        modifyingEntriesPair.ResolvePrivateKey(primaryKey);
                        if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("primaryKey.CheckExpectsAssignment()");
                    }
                }

                public override object GetRecordDataAfterAccess(int recordIndex, PrimaryKey primaryKey)
                {
                    if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
                    EnsureNoContextLockModifyingOnly();
                    EnsureAfterPopulatingEntries();
                    if (!ChangesApplied) throw new ApplicationException("!ChangesApplied");

                    EnsureMatchingResolvedPrimaryKey(recordIndex, primaryKey);
                    if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("primaryKey.CheckExpectsAssignment()");

                    var readRecordData = _reader.GetRecordDataAfterAccess(recordIndex, primaryKey);
                    var entry = _modifyingEntries[recordIndex].LockedOrCreatedRecordData
                        ?? throw new ApplicationException("_modifyingEntries[recordIndex].LockedOrCreatedRecordData == null");
                    if (readRecordData != null && entry.Entity != readRecordData)
                        throw new ApplicationException("readRecordData != null && entry.Entity != readRecordData");

                    if (_context.Database.CurrentTransaction == null)
                    {
                        if (entry.State != EntityState.Detached) throw new ApplicationException("entry.State != EntityState.Detached");
                    }
                    else
                    {
                        if (entry.State != EntityState.Unchanged) throw new ApplicationException("entry.State != EntityState.Unchanged");
                    }

                    return entry.Entity;
                }

                protected sealed override object GetExistingRecordDataIfReadByPrivateKey(long primaryKey)
                    => throw new ApplicationException(nameof(GetExistingRecordDataIfReadByPrivateKey));

                protected void EnsureNoUnexpectedContextChangesBeforeApplyingNewChanges()
                {
                    EnsureContextLockedModifyingOnly();
                    EnsureApplyingChanges();
                    if (!_context.ChangeTracker.AutoDetectChangesEnabled) throw new ApplicationException("!_context.ChangeTracker.AutoDetectChangesEnabled");
                    if (_context.ChangeTracker.Entries().Any(e => e.State != EntityState.Unchanged))
                        throw new ApplicationException("_context.ChangeTracker.Entries().Any(e => e.State != EntityState.Unchanged)");
                }
            }
        }
    }
}