using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using YourCompany.Configuration.EFCore.PessimisticLocking;
using YourCompany.OLTP.StateOwnership.Reflection.EFCore;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public partial class YourCompanyDbContext<TConfiguration>
    {
        public PropertyEntry<DelegatedPrimaryKeyGenerationTable, long>
            GeneratePrimaryKey<TRecordData, TQueryableRecordData>(PrimaryKey primaryKey)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
            EnsureLocked();

            Guid publicKey = primaryKey.CheckPublicKeyIsAssigned()
                ? primaryKey.PublicKey ?? throw new ApplicationException("!primaryKey.PublicKey.HasValue")
                : Guid.NewGuid();
            primaryKey.SetPublicKey(publicKey);
            if (!primaryKey.CheckPublicKeyIsAssigned()) throw new ApplicationException("!primaryKey.CheckPublicKeyIsAssigned()");

            var generatedPrivateKeyEntry = DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>()
                .Add(new DelegatedPrimaryKeyGenerationTable { PublicKey = publicKey })
                .Property<long>(nameof(DelegatedPrimaryKeyGenerationTable.AutoGeneratedPrimaryKey));

            var temporarilyGeneratedPrimaryKey = generatedPrivateKeyEntry.CurrentValue;
            if (temporarilyGeneratedPrimaryKey >= 0) throw new ApplicationException("emporarilyGeneratedPrimaryKey >= 0");
            primaryKey.SetPrivateKey(temporarilyGeneratedPrimaryKey);
            if (!primaryKey.CheckExpectsAssignment()) throw new ApplicationException("!primaryKey.CheckExpectsAssignment()");

            return generatedPrivateKeyEntry;
        }

        public PropertyEntry<DelegatedPrimaryKeyGenerationTable, long>
            AttachExistingPrimaryKeyWithMissingRecordData<TRecordData, TQueryableRecordData>(
            PrimaryKey primaryKey)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (primaryKey == null) throw new ArgumentNullException(nameof(primaryKey));
            if (primaryKey.CheckExpectsAssignment()) throw new ApplicationException("primaryKey.CheckExpectsAssignment()");
            EnsureLocked();

            long privateKey = primaryKey.PrivateKey ?? throw new ApplicationException("!primaryKey.PrivateKey.HasValue");

            var generatedPrivateKeyEntry = DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>()
                .Attach(new DelegatedPrimaryKeyGenerationTable
                {
                    PublicKey = primaryKey.PublicKey ?? throw new ApplicationException("!primaryKey.PublicKey.HasValue"),
                    AutoGeneratedPrimaryKey = privateKey
                })
                .Property<long>(nameof(DelegatedPrimaryKeyGenerationTable.AutoGeneratedPrimaryKey));

            if (generatedPrivateKeyEntry.CurrentValue != privateKey) throw new ApplicationException("generatedPrivateKeyEntry.CurrentValue != privateKey");
            return generatedPrivateKeyEntry;
        }

        public Task<List<RecordDataQueries.PrimaryKeyWithExists>> GetPrimaryKeys<TRecordData, TQueryableRecordData>(
            IEnumerable<Guid> publicKeys, CancellationToken cancellationToken)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (publicKeys == null) throw new ArgumentNullException(nameof(publicKeys));
            EnsureLocked();
            return DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>()
                .Where(primaryKey => publicKeys.Contains(primaryKey.PublicKey))
                .GroupJoin(
                    Set<TQueryableRecordData>(),
                    primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                    entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                    (primaryKey, singleEntityGroup) => new { PrimaryKey = primaryKey, SingleEntityGroup = singleEntityGroup })
                .SelectMany(
                    g => g.SingleEntityGroup.DefaultIfEmpty(),
                    (g, entity) => new
                    {
                        g.PrimaryKey,
                        Entity = entity
                    })
                .AsNoTracking()
                .Select(x => new RecordDataQueries.PrimaryKeyWithExists
                {
                    PublicKey = x.PrimaryKey.PublicKey,
                    PrivateKey = x.PrimaryKey.AutoGeneratedPrimaryKey,
                    RecordDataExists = x.Entity != null
                })
                .ToListAsync(cancellationToken);
        }

        public List<RecordDataQueries.PrimaryKeyWithExists>
            GetPrimaryKeysLocal<TRecordData, TQueryableRecordData>(IEnumerable<Guid> publicKeys)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (publicKeys == null) throw new ArgumentNullException(nameof(publicKeys));
            EnsureLocked();
            return DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>().Local
                .Where(primaryKey => publicKeys.Contains(primaryKey.PublicKey))
                .GroupJoin(
                    Set<TQueryableRecordData>().Local,
                    primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                    entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                    (primaryKey, singleEntityGroup) => new { PrimaryKey = primaryKey, SingleEntityGroup = singleEntityGroup })
                .SelectMany(
                    g => g.SingleEntityGroup.DefaultIfEmpty(),
                    (g, entity) => new
                    {
                        g.PrimaryKey,
                        Entity = entity
                    })
                .Select(x => new RecordDataQueries.PrimaryKeyWithExists
                {
                    PublicKey = x.PrimaryKey.PublicKey,
                    PrivateKey = x.PrimaryKey.AutoGeneratedPrimaryKey,
                    RecordDataExists = x.Entity != null
                })
                .ToList();
        }

        public Task<List<RecordDataQueries.PrimaryKeyWithExists>> GetPrimaryKeys<TRecordData, TQueryableRecordData>(
            IQueryable<TQueryableRecordData> queryable,
            CancellationToken cancellationToken)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (queryable == null) throw new ArgumentNullException(nameof(queryable));
            EnsureLocked();
            return queryable.AsNoTracking().Join(
                DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>(),
                entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                (_, primaryKey) => new RecordDataQueries.PrimaryKeyWithExists
                {
                    PublicKey = primaryKey.PublicKey,
                    PrivateKey = primaryKey.AutoGeneratedPrimaryKey,
                    RecordDataExists = true
                })
                .ToListAsync(cancellationToken);
        }

        public async Task<Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>>
            GetPrimaryKeysWithRecordDataToDictionary<TRecordData, TQueryableRecordData>(
                IReadOnlyList<long> privateKeys,
                bool lockAndTrack,
                CancellationToken cancellationToken)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (privateKeys == null) throw new ArgumentNullException(nameof(privateKeys));
            EnsureLocked();

            IQueryable<TQueryableRecordData> queryable = Set<TQueryableRecordData>();
            PessimisticLockingUpdateInterceptionContext lockContext = null;

            if (lockAndTrack)
            {
                if (Database.CurrentTransaction == null) throw new ApplicationException("lockAndTrack && Database.CurrentTransaction == null");
                var lastModifiedAtColumnName = GetLastModifiedAtColumnName(typeof(TRecordData));
                lockContext = StartPessimisticLockingInterception(
                    typeof(TQueryableRecordData), privateKeys, lastModifiedAtColumnName);
            }
            else
            {
                queryable = queryable.AsNoTracking();
            }

            try
            {
                queryable = lockContext?.Intercept(queryable) ?? queryable;
                return await GetPrimaryKeysWithRecordDataToDictionary<TRecordData, TQueryableRecordData>(
                    privateKeys, queryable, cancellationToken);
            }
            finally
            {
                lockContext?.Dispose();
            }
        }

        public Task<Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>>
            GetPrimaryKeysWithRecordDataToDictionary<TRecordData, TQueryableRecordData>(
                IReadOnlyList<long> privateKeys, IQueryable<TQueryableRecordData> queryable, CancellationToken cancellationToken)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (privateKeys == null) throw new ArgumentNullException(nameof(privateKeys));
            if (queryable == null) throw new ArgumentNullException(nameof(queryable));
            EnsureLocked();
            return queryable.Join(
                DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>(),
                entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                (entity, primaryKey) => new RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>
                {
                    PublicKey = primaryKey.PublicKey,
                    PrivateKey = primaryKey.AutoGeneratedPrimaryKey,
                    RecordData = entity
                })
                .Where(p => privateKeys.Contains(p.PrivateKey))
                .ToDictionaryAsync(p => p.PrivateKey, cancellationToken);
        }

        public Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>
            GetPrimaryKeysWithLocalRecordDataToDictionary<TRecordData, TQueryableRecordData>(
                IReadOnlyList<long> privateKeys)
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            if (privateKeys == null) throw new ArgumentNullException(nameof(privateKeys));
            EnsureLocked();

            var query = Set<TQueryableRecordData>().Local.Join(
                DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>().Local,
                entity => EF.Property<long>(entity, MetadataHelper.RecordDataNeverGeneratedBigintPrimaryKeyIdPropertyName),
                primaryKey => primaryKey.AutoGeneratedPrimaryKey,
                (entity, primaryKey) => new RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>
                {
                    PublicKey = primaryKey.PublicKey,
                    PrivateKey = primaryKey.AutoGeneratedPrimaryKey,
                    RecordData = entity
                })
                .Where(p => privateKeys.Contains(p.PrivateKey));

            Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>> result = null;

            foreach (var record in query)
            {
                result ??= new Dictionary<long, RecordDataQueries.PrimaryKeyWithRecordData<TQueryableRecordData>>();
                result.Add(record.PrivateKey, record);
            }

            return result;
        }

        public DbSet<DelegatedPrimaryKeyGenerationTable>
            DelegatedPrimaryKeyGenerationTableSet<TRecordData, TQueryableRecordData>()
            where TRecordData : class
            where TQueryableRecordData : class, TRecordData
        {
            var queryableRecordDataType = GetQueryableRecordDataType(typeof(TRecordData));
            if (queryableRecordDataType != typeof(TQueryableRecordData)) throw new ApplicationException("queryableRecordDataType != typeof(TQueryableRecordData)");
            string tableName = Model.FindEntityType(queryableRecordDataType)?.GetTableName() ?? throw new ApplicationException("tableName == null");
            return Set<DelegatedPrimaryKeyGenerationTable>(
                name: tableName + DelegatedPrimaryKeyGenerationTable.EntityTableNameSuffix);
        }

        protected virtual void DeclarePrimaryKey(
            ModelBuilder modelBuilder, Type recordDataType, Type queryableRecordDataType)
            => modelBuilder.DeclareRecordDataDelegatedBigintPrimaryKeyGeneratedProperty(queryableRecordDataType);
    }
}