using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using YourCompany.OLTP.StateOwnership;
using YourCompany.Reflection;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public abstract partial class YourCompanyDbContextLockingRecordDataReader<TConfiguration>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        private static class FactoriesCache
        {
            private static readonly Expression<Func<object>> SingleEntityQueryByIdsWithoutForcedReadIfModifyingConstructor
                = () => new SingleEntityQuery<object, object>
                    .ByIds
                    .WithoutForcedReadIfModifying(null, null);

            private static readonly ConcurrentDictionary
                <(Type, Type), Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryByIdsWithoutForcedReadIfModifyingFactoryByRecordType = new();

            private static readonly Func
                <(Type, Type), Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryByIdsWithoutForcedReadIfModifyingFactoryByRecordTypeCreateItemNonExclusiveStrategy
                    = singleEntityQueryTypeArguments =>
                    {
                        var context = Expression.Parameter(typeof(object), "context");
                        var ids = Expression.Parameter(typeof(object), "ids");
                        var constructor = Expression.New(
                            GetSingleEntityQueryConstructor(
                                SingleEntityQueryByIdsWithoutForcedReadIfModifyingConstructor,
                                singleEntityQueryTypeArguments),
                            Expression.Convert(context, typeof(YourCompanyDbContext<TConfiguration>)),
                            Expression.Convert(ids, typeof(IReadOnlyList<PrimaryKey>)));
                        return Expression
                            .Lambda<Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>(
                                constructor, context, ids)
                            .Compile();
                    };

            private static readonly Expression<Func<object>> SingleEntityQueryByIdsWithForcedReadIfModifyingConstructor
                = () => new SingleEntityQuery<object, object>
                    .ByIds
                    .WithForcedReadIfModifying(null, null);

            private static readonly ConcurrentDictionary
                <(Type, Type), Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryByIdsWithForcedReadIfModifyingFactoryByRecordType = new();

            private static readonly Func
                <(Type, Type), Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryByIdsWithForcedReadIfModifyingFactoryByRecordTypeCreateItemNonExclusiveStrategy
                    = singleEntityQueryTypeArguments =>
                    {
                        var context = Expression.Parameter(typeof(object), "context");
                        var ids = Expression.Parameter(typeof(object), "ids");
                        var constructor = Expression.New(
                            GetSingleEntityQueryConstructor(
                                SingleEntityQueryByIdsWithForcedReadIfModifyingConstructor,
                                singleEntityQueryTypeArguments),
                            Expression.Convert(context, typeof(YourCompanyDbContext<TConfiguration>)),
                            Expression.Convert(ids,
                                typeof(IReadOnlyList<PrimaryKey>)));
                        return Expression
                            .Lambda<Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>(
                                constructor, context, ids)
                            .Compile();
                    };

            private static readonly Expression<Func<object>> SingleEntityQueryWithoutIdsAfterConstructor
                = () => new SingleEntityQuery<object, object>
                    .WithoutIds
                    .After(null, null);

            private static readonly ConcurrentDictionary
                <(Type, Type), Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryWithoutIdsAfterFactoryByRecordType = new();

            private static readonly Func
                <(Type, Type), Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryWithoutIdsAfterFactoryByRecordTypeCreateItemNonExclusiveStrategy
                    = singleEntityQueryTypeArguments =>
                    {
                        var context = Expression.Parameter(typeof(object), "context");
                        var afterId = Expression.Parameter(typeof(Identity), "afterId");
                        var constructor = Expression.New(
                            GetSingleEntityQueryConstructor(
                                SingleEntityQueryWithoutIdsAfterConstructor,
                                singleEntityQueryTypeArguments),
                            Expression.Convert(context, typeof(YourCompanyDbContext<TConfiguration>)),
                            Expression.Convert(afterId, typeof(Identity)));
                        return Expression
                            .Lambda<Func<object, object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>(
                                constructor, context, afterId)
                            .Compile();
                    };

            private static readonly Expression<Func<object>> SingleEntityQueryWithoutIdsNoSortingConstructor
                = () => new SingleEntityQuery<object, object>
                    .WithoutIds
                    .NoSorting(null);

            private static readonly ConcurrentDictionary
                <(Type, Type), Func<object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryWithoutIdsNoSortingFactoryByRecordType = new();

            private static readonly Func
                <(Type, Type), Func<object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>
                SingleEntityQueryWithoutIdsNoSortingFactoryByRecordTypeCreateItemNonExclusiveStrategy
                    = singleEntityQueryTypeArguments =>
                    {
                        var context = Expression.Parameter(typeof(object), "context");
                        var constructor = Expression.New(
                            GetSingleEntityQueryConstructor(
                                SingleEntityQueryWithoutIdsNoSortingConstructor,
                                singleEntityQueryTypeArguments),
                            Expression.Convert(context, typeof(YourCompanyDbContext<TConfiguration>)));
                        return Expression
                            .Lambda<Func<object, YourCompanyDbContextLockingRecordDataReader<TConfiguration>>>(
                                constructor, context)
                            .Compile();
                    };

            internal static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
                ByIdsWithoutForcedReadIfModifying(
                    Type recordDataType,
                    Type queryableRecordDataType,
                    YourCompanyDbContext<TConfiguration> context,
                    IReadOnlyList<PrimaryKey> ids)
                    => SingleEntityQueryByIdsWithoutForcedReadIfModifyingFactoryByRecordType.GetOrAdd(
                            (recordDataType, queryableRecordDataType),
                            SingleEntityQueryByIdsWithoutForcedReadIfModifyingFactoryByRecordTypeCreateItemNonExclusiveStrategy)
                        .Invoke(context, ids);

            internal static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
                ByIds(
                    Type recordDataType,
                    Type queryableRecordDataType,
                    YourCompanyDbContext<TConfiguration> context,
                    IReadOnlyList<Identity> ids)
                    => SingleEntityQueryByIdsWithForcedReadIfModifyingFactoryByRecordType.GetOrAdd(
                            (recordDataType, queryableRecordDataType),
                            SingleEntityQueryByIdsWithForcedReadIfModifyingFactoryByRecordTypeCreateItemNonExclusiveStrategy)
                        .Invoke(context, ids);

            internal static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
                After(
                    Type recordDataType,
                    Type queryableRecordDataType,
                    YourCompanyDbContext<TConfiguration> context,
                    Identity afterId)
                    => SingleEntityQueryWithoutIdsAfterFactoryByRecordType.GetOrAdd(
                            (recordDataType, queryableRecordDataType),
                            SingleEntityQueryWithoutIdsAfterFactoryByRecordTypeCreateItemNonExclusiveStrategy)
                        .Invoke(context, afterId);

            internal static YourCompanyDbContextLockingRecordDataReader<TConfiguration>
                NoSorting(Type recordDataType, Type queryableRecordDataType, YourCompanyDbContext<TConfiguration> context)
                    => SingleEntityQueryWithoutIdsNoSortingFactoryByRecordType.GetOrAdd(
                            (recordDataType, queryableRecordDataType),
                            SingleEntityQueryWithoutIdsNoSortingFactoryByRecordTypeCreateItemNonExclusiveStrategy)
                        .Invoke(context);

            private static ConstructorInfo GetSingleEntityQueryConstructor(
                Expression<Func<object>> constructorExpression, (Type, Type) singleEntityQueryTypeArguments)
            {
                var constructor = GetMemberHelper.GetConstructorInfo(constructorExpression);
                constructor.DeclaringType.GetGenericTypeDefinition();
                var parameterTypes = constructor.GetParameters().Select(p => p.ParameterType).ToArray();
                return constructor.DeclaringType.GetGenericTypeDefinition()
                    .MakeGenericType(
                        typeof(TConfiguration), singleEntityQueryTypeArguments.Item1, singleEntityQueryTypeArguments.Item2)
                    .GetConstructor(parameterTypes) ?? throw new ApplicationException("constructor == null");
            }
        }
    }
}