using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using YourCompany.OLTP.StateOwnership;

using PrimaryKey = YourCompany.OLTP.RecordsManagement.Persistence
    .UniqueKey.Primary.PublicGuidAccompanied.PrivateInsertFailureTolerantAutoGeneratedBigint;

namespace YourCompany.OLTP.RecordsManagement.Persistence.Linq.EFCore
{
    public class YourCompanyDbContextRecordsDataAccessAdapter<TConfiguration> : RecordsDataAccess.IStarting,
        RecordsDataAccess.IAfterSortingByIds,
        RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting>,
        RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues>
        where TConfiguration : YourCompanyDbContextConfiguration, new()
    {
        private bool _disposed;
        private YourCompanyDbContextLockingRecordDataReader<TConfiguration> _reader;

        protected Type RecordDataType { get; }
        protected YourCompanyDbContext<TConfiguration> Context { get; }
        protected bool ContextCreator { get; }

        public YourCompanyDbContextRecordsDataAccessAdapter(
            Type recordDataType, YourCompanyDbContext<TConfiguration> context, bool contextCreator)
        {
            RecordDataType = recordDataType ?? throw new ArgumentNullException(nameof(recordDataType));
            Context = context ?? throw new ArgumentNullException(nameof(context));
            ContextCreator = contextCreator;
        }

        public int MaxRecordsInBatch
            => Context.Configuration.ByRecordDataTypeFullName?.TryGetValue(RecordDataType.FullName, out var by) == true
                ? by.MaxRecordsInBatch ?? Context.Configuration.DefaultMaxRecordsInBatch
                : Context.Configuration.DefaultMaxRecordsInBatch;

        public virtual RecordsDataAccess.IAfterSortingByIdsWithoutReading ByIdsWithoutForcedReadIfModifying(
            IReadOnlyList<PrimaryKey> ids)
        {
            EnsureNotDisposed();
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.ByIdsWithoutForcedReadIfModifying(
                RecordDataType, queryableRecordDataType, Context, ids);
            return null;
        }

        public virtual RecordsDataAccess.IAfterSortingByIds ByIds(
            IReadOnlyList<Identity> ids, bool skipMissingOrPreventCreation)
        {
            EnsureNotDisposed();
            if (_reader != null)
            {
                if (!ReferenceEquals(_reader.PrimaryKeys, ids))
                    throw new ApplicationException("!ReferenceEquals(_reader.PrimaryKeys, ids)");
                return this;
            }
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.ByIds(
                RecordDataType, queryableRecordDataType, Context, ids, skipMissingOrPreventCreation);
            return this;
        }

        public virtual RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.AfterAlternateSorting> After(Identity afterId)
        {
            EnsureNotDisposed();
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.After(
                RecordDataType, queryableRecordDataType, Context, afterId);
            return this;
        }

        public virtual RecordsDataAccess.IAfterSortingWithoutIds<PrimaryKey.WithoutExtraValues> NoSorting()
        {
            EnsureNotDisposed();
            if (_reader != null) throw new ApplicationException("_reader != null");
            var queryableRecordDataType = Context.GetQueryableRecordDataType(RecordDataType) ?? throw new ApplicationException("queryableRecordDataType == null");
            _reader = YourCompanyDbContextLockingRecordDataReader<TConfiguration>.NoSorting(
                RecordDataType, queryableRecordDataType, Context);
            return this;
        }

        public bool FilterAfterSorting(object specification)
        {
            EnsureNotDisposed();
            if (specification == null) throw new ArgumentNullException(nameof(specification));
            if (_reader == null) throw new ApplicationException("_reader == null");
            return _reader.FilterAfterSortingWithoutIds(specification);
        }

        RecordsDataAccess.IReadOnly<PrimaryKey>
            RecordsDataAccess.IAfterSortingByIdsForReadOnly
                .ForReadOnlyByIdsWithoutRecordsData() => _reader?.ForReadOnlyByIdsWithoutRecordsData();

        RecordsDataAccess.IReadOnly<PrimaryKey>
            RecordsDataAccess.IAfterSortingByIdsForReadOnly
                .ForReadOnlyByIdsWithRecordsData() => _reader?.ForReadOnlyByIdsWithRecordsData();

        RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
            RecordsDataAccess.IAfterSortingWithoutIdsForReadOnlyWithoutRecordsData
                .ForReadOnlyWithoutRecordsData() => _reader?.ForReadOnlyWithoutIdsWithoutRecordsData();

        RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.AfterAlternateSorting>
            RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.AfterAlternateSorting>
                .ForReadOnlyWithRecordsData() => _reader?.ForReadOnlyWithoutIdsWithRecordsDataAfterAlternateSorting();

        RecordsDataAccess.IReadOnlyWithoutIds<PrimaryKey.WithoutExtraValues>
            RecordsDataAccess.IAfterSortingWithoutIdsForReadOnly<PrimaryKey.WithoutExtraValues>
                .ForReadOnlyWithRecordsData() => _reader?.ForReadOnlyWithoutIdsWithRecordsDataWithoutExtraValues();

        RecordsDataAccess.IReadBeforeModifying<PrimaryKey>
            RecordsDataAccess.IAfterSortingByIdsForModifying.ForModifyingAfterReadingByIds() => null;

        RecordsDataAccess.IReadBeforeModifying<PrimaryKey.AfterAlternateSorting>
            RecordsDataAccess.IAfterSortingWithoutIdsForModifying<PrimaryKey.AfterAlternateSorting>
                .ForModifyingAfterReading() => null;

        RecordsDataAccess.IReadBeforeModifying<PrimaryKey.WithoutExtraValues>
            RecordsDataAccess.IAfterSortingWithoutIdsForModifying<PrimaryKey.WithoutExtraValues>
                .ForModifyingAfterReading() => null;

        public async virtual Task Dispose(CancellationToken cancellationToken, Exception runException = null)
        {
            bool wasDisposed = _disposed;
            _disposed = true;

            var reader = _reader;
            _reader = null;

            if (wasDisposed && reader != null)
                throw new ApplicationException("wasDisposed && reader != null", runException);

            if (wasDisposed) return;

            if (reader != null && reader.ContextIsLocked) reader.ReleaseContextLock();

            if (!ContextCreator) return;

            var disposeLock = new TaskCompletionSource();
            await Context.Lock(disposeLock.Task);

            Exception rollbackException = null;

            try
            {
                try
                {
                    await Context.DisposeAsync();
                }
                catch (Exception) when (rollbackException == null)
                {
                    throw;
                }
                catch (Exception ex) when (rollbackException != null)
                {
                    throw new AggregateException(rollbackException, ex);
                }
            }
            catch (Exception ex) when (runException == null)
            {
                disposeLock.SetException(ex);
                throw;
            }
            catch (Exception ex) when (runException != null)
            {
                var disposeException = new AggregateException(runException, ex);
                disposeLock.SetException(disposeException);
                throw disposeException;
            }

            disposeLock.SetResult();
        }

        protected void EnsureNotDisposed()
        {
            if (_disposed) throw new ObjectDisposedException(nameof(YourCompanyDbContextRecordsDataAccessAdapter<TConfiguration>));
        }
    }
}